// Backend Interview Answers - Node.js, Express.js, MongoDB, Python, Django, FastAPI
export const BACKEND_ANSWERS = {
    nodejs: {
        easy: {
            "What is Node.js and what are its key features?": "Node.js is JavaScript runtime built on V8 engine. Key features: Non-blocking I/O, event-driven, single-threaded, npm ecosystem, cross-platform. Used for servers, APIs, real-time apps.",
            "What is the difference between Node.js and JavaScript?": "JavaScript: Programming language for browsers. Node.js: Runtime environment to run JS outside browser. Node adds: fs, http, os modules. Browser has: DOM, window object.",
            "What is npm and what is package.json?": "npm: Node Package Manager for installing/managing packages. package.json: Project manifest with dependencies, scripts, metadata. npm install reads it. Defines project configuration.",
            "What is the event loop in Node.js?": "Event loop handles async operations. Phases: Timers, I/O callbacks, idle, poll, check, close. Allows non-blocking I/O on single thread. Core of Node.js async behavior.",
            "What are modules in Node.js?": "Modules are reusable code blocks. Types: Core (fs, http), Local (your files), Third-party (npm). Use require() or import. Each file is a module with own scope.",
            "What is the difference between require() and import?": "require(): CommonJS, synchronous, dynamic. import: ES Modules, async, static analysis, tree-shaking. Use import for modern projects. Add \"type\": \"module\" in package.json.",
            "What is callback in Node.js?": "Callback: Function passed as argument, called after async operation completes. Convention: Error-first (err, result). Foundation of async Node.js. Can lead to callback hell.",
            "What is the difference between synchronous and asynchronous functions?": "Sync: Blocks execution until complete. Async: Non-blocking, continues execution, uses callbacks/promises. Use async for I/O operations. Sync blocks event loop.",
            "What is Buffer in Node.js?": "Buffer: Raw binary data storage. Used for: File operations, network protocols, binary data. Fixed size, allocated outside V8 heap. Buffer.from(), Buffer.alloc().",
            "What is the difference between process.nextTick() and setImmediate()?": "process.nextTick(): Executes before I/O events in current phase. setImmediate(): Executes in check phase after I/O. nextTick higher priority, can starve I/O.",
            "What is the global object in Node.js?": "global: Node's global namespace (like window in browser). Contains: process, Buffer, setTimeout, console. Avoid polluting global scope. Use module.exports instead.",
            "What is __dirname and __filename in Node.js?": "__dirname: Absolute path to current directory. __filename: Absolute path to current file. CommonJS only. ES modules use import.meta.url instead.",
            "What is the purpose of module.exports?": "module.exports: Exports values from module. Accessed via require(). Can export: Objects, functions, classes. exports is shorthand reference to module.exports.",
            "What are streams in Node.js?": "Streams: Handle data flow in chunks. Types: Readable, Writable, Duplex, Transform. Memory efficient for large files. Pipe connects streams. EventEmitter based.",
            "What is the difference between readFile and createReadStream?": "readFile: Loads entire file in memory, simpler. createReadStream: Reads in chunks, memory efficient for large files. Use stream for files >100MB.",
            "What is middleware in Node.js?": "Middleware: Functions with access to req, res, next. Process requests before reaching route handler. Used for: Auth, logging, parsing, error handling.",
            "What is the purpose of package-lock.json?": "package-lock.json: Locks exact dependency versions. Ensures consistent installs across environments. Auto-generated. Commit to version control.",
            "What is the difference between dependencies and devDependencies?": "dependencies: Required for production. devDependencies: Only for development (testing, building). npm install --production skips devDependencies.",
            "What is nodemon and why is it used?": "nodemon: Auto-restarts server on file changes. Used in development. Install: npm install -g nodemon. Run: nodemon app.js instead of node app.js.",
            "What is the difference between local and global installation of packages?": "Local: Installed in node_modules, project-specific. Global (-g): Available system-wide, CLI tools. Prefer local for project dependencies.",
            "What is the purpose of .gitignore in Node.js projects?": ".gitignore: Files/folders excluded from git. Include: node_modules, .env, logs, build folders. Prevents committing large/sensitive files.",
            "What is the difference between blocking and non-blocking code?": "Blocking: Waits for operation to complete. Non-blocking: Returns immediately, callback later. Node.js async methods are non-blocking. Blocking bad for scalability.",
            "What is callback hell and how to avoid it?": "Callback hell: Nested callbacks, hard to read/maintain. Solutions: Promises, async/await, named functions, modularization. Flatten async code structure.",
            "What is the purpose of util.promisify()?": "util.promisify(): Converts callback-based functions to Promise. Example: promisify(fs.readFile). Enables async/await with older APIs.",
            "What is the difference between setTimeout and setInterval?": "setTimeout: Executes once after delay. setInterval: Repeats at interval. Both async. clearTimeout/clearInterval to cancel. setInterval can drift.",
        },
        medium: {
            "How do you handle errors in Node.js?": "Error handling: try/catch for sync, .catch() for promises, error-first callbacks, process.on('uncaughtException'), Express error middleware. Always handle errors.",
            "What are Promises and how do they work in Node.js?": "Promises: Represent eventual completion/failure. States: Pending, Fulfilled, Rejected. Methods: .then(), .catch(), .finally(). Promise.all(), Promise.race().",
            "What is async/await and how is it different from Promises?": "async/await: Syntactic sugar for Promises. Cleaner code, better error handling with try/catch. async function returns Promise. await pauses execution.",
            "How do you create a simple HTTP server in Node.js?": "Use http module: http.createServer((req, res) => { res.end('Hello') }).listen(3000). Handle requests with req.url, req.method. Prefer Express for complex apps.",
            "What is clustering in Node.js and why is it important?": "Clustering: Run multiple Node processes. Uses all CPU cores. Master spawns workers. Built-in cluster module. Improves performance and reliability.",
            "How do you handle file operations in Node.js?": "fs module: readFile, writeFile, appendFile, unlink. Sync and async versions. Use streams for large files. Handle errors properly.",
            "What is the difference between spawn, exec, and fork?": "spawn: Streams stdio, for long processes. exec: Buffers output, for short commands. fork: Special spawn for Node processes, IPC channel. Choose based on use case.",
            "How do you implement authentication in Node.js?": "Options: Sessions (express-session), JWT (jsonwebtoken), Passport.js. Hash passwords (bcrypt). HTTPS always. Secure cookies. Rate limiting.",
            "What is JWT and how do you implement it?": "JWT: JSON Web Token for stateless auth. Structure: Header.Payload.Signature. Use jsonwebtoken library. Store in httpOnly cookie or header. Verify on each request.",
            "How do you handle environment variables in Node.js?": "process.env for access. dotenv package loads .env file. Never commit .env. Different files for environments. Validate required variables at startup.",
            "What is the purpose of cors and how do you implement it?": "CORS: Cross-Origin Resource Sharing. Use cors middleware. Configure: origin, methods, credentials. Security for cross-domain requests. Default: same-origin only.",
            "How do you implement rate limiting in Node.js?": "express-rate-limit package. Configure: windowMs, max requests. Store: Memory, Redis. Prevent abuse, DDoS protection. Different limits for different routes.",
            "What is the difference between cookie and session?": "Cookie: Client-side storage, sent with requests. Session: Server-side storage, uses session ID cookie. Sessions more secure for sensitive data.",
            "How do you implement logging in Node.js applications?": "winston or pino for logging. Levels: error, warn, info, debug. File and console transports. Structured JSON logs. Include timestamp, request ID.",
            "What is the purpose of helmet.js?": "helmet: Security middleware. Sets HTTP headers: Content-Security-Policy, X-Frame-Options, etc. Defense against XSS, clickjacking. Essential for production.",
            "How do you handle database connections in Node.js?": "Use connection pools. Connection strings from env vars. Handle connection errors. Retry logic. Close connections on shutdown. ORM or direct driver.",
            "What is connection pooling and why is it important?": "Connection pooling: Reuse database connections. Faster than creating new connections. Limit pool size. Prevents connection exhaustion. Built into most drivers.",
            "How do you implement caching in Node.js?": "Options: In-memory (node-cache), Redis, Memcached. Cache frequently accessed data. TTL for expiration. Cache invalidation strategy. Improves performance.",
            "What is the difference between PUT and PATCH methods?": "PUT: Replace entire resource. PATCH: Partial update. PUT idempotent. PATCH may not be. Use PATCH for partial updates to reduce payload.",
            "How do you implement file upload in Node.js?": "multer middleware for Express. Handles multipart/form-data. Configure: Storage, limits, file filter. Save to disk or cloud storage.",
            "What is the purpose of body-parser middleware?": "body-parser: Parses request body. express.json() and express.urlencoded() built-in now. Parses JSON and form data. Required for POST/PUT requests.",
            "How do you handle validation in Node.js APIs?": "Joi, Yup, or express-validator. Validate: Body, params, query. Return clear error messages. Sanitize input. Never trust client data.",
            "What is the difference between development and production environments?": "Development: Debug logging, hot reload, verbose errors. Production: Minified, optimized, secure, no sensitive logs. Use NODE_ENV to distinguish.",
            "How do you implement testing in Node.js?": "Jest or Mocha for testing. Supertest for API tests. Mock dependencies. Unit, integration, e2e tests. Coverage reports. CI/CD integration.",
            "What is the purpose of PM2 in Node.js deployment?": "PM2: Process manager. Features: Cluster mode, auto-restart, logs, monitoring. Zero-downtime reload. Production-ready. pm2 start app.js -i max.",
        },
        hard: {
            "How do you optimize Node.js application performance?": "Profiling (clinic.js), clustering, caching, connection pooling, avoid blocking operations, stream large data, optimize queries, lazy loading, CDN for static files.",
            "How do you implement microservices architecture with Node.js?": "Separate services by domain, API gateway, message queues (RabbitMQ), service discovery, containerization, independent databases, circuit breakers, distributed tracing.",
            "How do you handle memory leaks in Node.js applications?": "Identify: heapdump, clinic.js. Causes: Global variables, closures, event listeners, caches. Fix: Remove listeners, limit caches, weak references. Monitor heap.",
            "What is the V8 engine and how does it work with Node.js?": "V8: Google's JS engine in Chrome/Node. Compiles JS to machine code. JIT compilation Optimizes hot code. Garbage collection. Node adds libuv for async I/O.",
            "How do you implement real-time communication with WebSockets?": "ws or socket.io library. Bidirectional communication. Events: connection, message, disconnect. Rooms for grouping. Scale with Redis adapter.",
            "How do you handle large file uploads efficiently?": "Streams for memory efficiency, chunked uploads, resumable uploads, cloud storage (S3), progress tracking, size limits, virus scanning.",
            "What is the difference between horizontal and vertical scaling?": "Vertical: More resources per server (CPU, RAM). Horizontal: More servers. Horizontal better for Node.js. Load balancer distributes requests.",
            "How do you implement distributed caching with Redis?": "Redis as central cache. Commands: GET, SET, EXPIRE. Data structures: Strings, hashes, lists. Pub/sub for invalidation. Cluster for HA.",
            "How do you handle database transactions in Node.js?": "Begin transaction, execute queries, commit or rollback on error. ORMs have transaction support. Handle failures gracefully. Avoid long transactions.",
            "What is the purpose of load balancing in Node.js applications?": "Load balancing distributes traffic across servers. Options: Nginx, HAProxy, cloud LBs. Algorithms: Round robin, least connections. Health checks.",
            "How do you implement API versioning?": "Options: URL path (/v1/), header (Accept-Version), query param. URL path most common. Maintain backward compatibility. Deprecation notices.",
            "How do you handle graceful shutdown in Node.js?": "Listen for SIGTERM/SIGINT. Stop accepting connections, finish pending requests, close database connections, then exit. PM2 handles this automatically.",
            "What is the difference between stateful and stateless applications?": "Stateless: No session on server, scales easily. Stateful: Server holds state, sticky sessions needed. Prefer stateless with external session store.",
            "How do you implement message queues with Node.js?": "RabbitMQ, Redis, AWS SQS. Publisher/subscriber pattern. Decouple services. Handle failures with retries. Dead letter queues for failed messages.",
            "How do you handle concurrent requests efficiently?": "Event loop handles concurrency. Use worker threads for CPU tasks. Connection pooling. Caching. Rate limiting. Optimize database queries.",
            "What is the purpose of reverse proxy in Node.js deployment?": "Nginx/Caddy as reverse proxy. Benefits: SSL termination, load balancing, caching, compression, security headers. Node behind proxy, not public.",
            "How do you implement database sharding?": "Sharding: Split data across databases. Shard key determines location. Reduces single DB load. Complexity: Cross-shard queries, rebalancing.",
            "How do you handle API security and prevent common attacks?": "HTTPS, input validation, rate limiting, helmet, CORS, SQL injection prevention, XSS prevention, authentication, authorization, audit logs.",
            "What is the difference between monolithic and microservices architecture?": "Monolithic: Single codebase, simpler to develop/deploy. Microservices: Independent services, scalable, complex. Start monolith, split when needed.",
            "How do you implement distributed tracing in Node.js?": "Jaeger, Zipkin, or OpenTelemetry. Trace requests across services. Correlation IDs. Identify bottlenecks. Essential for microservices debugging.",
            "How do you handle database migrations in production?": "Migration tools (Knex, Sequelize). Version controlled. Test in staging. Backup before. Backward compatible. Rollback plan. Zero-downtime.",
            "What is the purpose of container orchestration?": "Kubernetes, Docker Swarm. Manage containers at scale. Auto-scaling, self-healing, rolling updates. Load balancing. Service discovery.",
            "How do you implement circuit breaker pattern?": "opossum library. Track failures. Open circuit after threshold. Fail fast. Half-open to test recovery. Prevents cascade failures.",
            "How do you handle eventual consistency in distributed systems?": "Accept delayed consistency. Saga pattern for transactions. Idempotent operations. Compensating transactions. Event sourcing. CQRS.",
            "How do you implement event-driven architecture with Node.js?": "EventEmitter for local. Kafka/RabbitMQ for distributed. Publish events, subscribers react. Loose coupling. Async processing. Event store.",
        }
    },
    expressjs: {
        easy: {
            "What is Express.js and why is it used?": "Express.js: Minimal, flexible Node.js web framework. Used for APIs, web apps. Features: Routing, middleware, template engines. De facto standard for Node web development.",
            "How do you create a basic Express.js application?": "const express = require('express'); const app = express(); app.get('/', (req, res) => res.send('Hello')); app.listen(3000);",
            "What is routing in Express.js?": "Routing: Defining how app responds to client requests. app.METHOD(PATH, HANDLER). Methods: get, post, put, delete. Route parameters: /users/:id.",
            "What are route parameters and query parameters?": "Route params: Part of URL path (/users/:id). Query params: After ? (?name=john). Access: req.params.id, req.query.name.",
            "What is middleware in Express.js?": "Middleware: Functions with access to req, res, next. Execute code, modify request/response, end cycle, call next(). Crucial for Express apps.",
            "What is the difference between app.use() and app.get()?": "app.use(): Applies middleware to all routes. app.get(): Handles GET requests for specific path. use() for middleware, get/post/etc for routes.",
            "How do you serve static files in Express.js?": "express.static() middleware: app.use(express.static('public')). Serves files from public folder. Configure: Index, extensions, caching.",
            "What is the purpose of express.Router()?": "Router: Modular route handlers. Create mini-app. Group related routes. Mount with app.use('/api', router). Better organization.",
            "How do you handle POST requests in Express.js?": "app.post('/path', (req, res) => {}). Parse body: express.json() or express.urlencoded(). Access data: req.body.",
            "What is the difference between req and res objects?": "req: Request object (URL, params, body, headers). res: Response object (send, json, status, redirect). req for input, res for output.",
            "How do you parse JSON data in Express.js?": "app.use(express.json()). Parses JSON request bodies. Access via req.body. Set Content-Type: application/json.",
            "What is the purpose of next() function in middleware?": "next(): Passes control to next middleware. Without it, request hangs. next(err) for error handling. Chain middleware functions.",
            "How do you handle route parameters in Express.js?": "Define: /users/:id. Access: req.params.id. Multiple: /users/:userId/posts/:postId. Optional: /:id?. Regex validation possible.",
            "What is the difference between app.listen() and server.listen()?": "app.listen() shorthand creates http server. server.listen() for custom server (HTTPS, WebSocket). Both start listening on port.",
            "How do you set up basic error handling in Express.js?": "Error middleware: app.use((err, req, res, next) => {}). Must have 4 parameters. Defined last. Use try/catch in async routes.",
            "What is the purpose of express.json() middleware?": "express.json(): Parses JSON request bodies. Built-in body-parser. Returns parsed data in req.body. Only parses Content-Type: application/json.",
            "How do you implement basic authentication in Express.js?": "Check credentials in middleware. Compare password hash (bcrypt). Set session or return JWT. Protect routes with auth middleware.",
            "What is the difference between GET and POST requests?": "GET: Retrieve data, params in URL, cacheable, bookmarkable. POST: Send data, body payload, not cached, for mutations.",
            "How do you handle cookies in Express.js?": "cookie-parser middleware. Read: req.cookies. Set: res.cookie('name', 'value', options). Clear: res.clearCookie('name'). Options: maxAge, httpOnly, secure.",
            "What is the purpose of express.urlencoded() middleware?": "Parses URL-encoded form data. app.use(express.urlencoded({ extended: true })). Extended: Nested objects. For HTML form submissions.",
            "How do you implement basic logging in Express.js?": "morgan middleware: app.use(morgan('dev')). Formats: combined, common, dev. Custom formats. File logging with stream option.",
            "What is the difference between middleware and route handlers?": "Middleware: Process requests, can call next(). Route handlers: End request-response cycle (send response). Both are functions with same signature.",
            "How do you handle multiple route methods for the same path?": "app.route('/path').get(handler).post(handler).put(handler). Chain methods. DRY approach. Single path definition.",
            "What is the purpose of app.all() method?": "app.all(): Handles ALL HTTP methods for a path. Used for common middleware before specific methods. Runs before get/post/etc.",
            "How do you implement basic session management?": "express-session middleware. Configure: Secret, store, cookie options. req.session for data. Store sessions in Redis/database for production.",
        },
        medium: {
            "How do you implement custom middleware in Express.js?": "Function with (req, res, next). Modify req/res, log, authenticate. Call next() to continue. Return response to end. Can be async.",
            "What is error handling middleware and how do you implement it?": "4 parameters: (err, req, res, next). Catch thrown errors. Handle async errors with express-async-handler. Log and return error response.",
            "How do you implement input validation in Express.js?": "express-validator or Joi. Validate body, params, query. Middleware approach. Return 400 with error details. Sanitize data.",
            "What is the purpose of helmet middleware?": "helmet: Sets security headers. Prevents XSS, clickjacking, MIME sniffing. app.use(helmet()). Configure individual protections. Production essential.",
            "How do you implement CORS in Express.js applications?": "cors package: app.use(cors({ origin, credentials })). Allow specific origins, methods. Handle preflight. Whitelist trusted domains.",
            "What is the difference between application-level and router-level middleware?": "App-level: app.use(), applies globally. Router-level: router.use(), applies to router only. Same signature. Different scope.",
            "How do you implement rate limiting in Express.js?": "express-rate-limit: Configure windowMs, max requests. Return 429 Too Many Requests. Redis store for distributed. Different limits per route.",
            "What is the purpose of compression middleware?": "compression: Gzip response bodies. Reduces transfer size. app.use(compression()). Threshold option. Significant performance improvement.",
            "How do you handle file uploads in Express.js?": "multer middleware. Configure: storage, limits, fileFilter. Single/multiple files. Disk or memory storage. Handle with req.file(s).",
            "How do you implement JWT authentication in Express.js?": "jsonwebtoken: sign() to create, verify() to validate. Middleware checks Authorization header. Decode payload to req.user. Handle expiration.",
            "What is the difference between cookie-parser and express-session?": "cookie-parser: Parses cookies. express-session: Full session management with storage. Use together: session ID in cookie, data in store.",
            "How do you implement API versioning in Express.js?": "URL prefix: /api/v1/, /api/v2/. Separate routers per version. Header-based also possible. Maintain backward compatibility.",
            "What is the purpose of morgan middleware for logging?": "morgan: HTTP request logger. Predefined formats. Custom tokens. Stream to file. Essential for debugging and monitoring.",
            "How do you handle database integration in Express.js?": "Choose driver/ORM (Mongoose, Sequelize). Connect in app startup. Handle connection errors. Use connection pooling. Close on shutdown.",
            "What is the difference between synchronous and asynchronous middleware?": "Sync: Direct flow, next() called at end. Async: Use async/await, wrap with error handler, or express-async-handler.",
            "How do you implement custom error pages in Express.js?": "Error middleware returns HTML. 404 handler for not found. Status code determines page. Template engine for dynamic pages.",
            "What is the purpose of express-validator?": "Validation middleware. check(), body(), param(), query(). Sanitization. validationResult() to get errors. Chain validations.",
            "How do you implement pagination in Express.js APIs?": "Query params: page, limit. Calculate skip. Return total count. Include next/prev links. Default limits. Cap maximum.",
            "What is the difference between res.send() and res.json()?": "res.send(): Any type, sets Content-Type. res.json(): Converts to JSON, sets application/json. Use json() for APIs.",
            "How do you implement caching headers in Express.js?": "res.set('Cache-Control', 'max-age=3600'). express-cache-headers middleware. ETags built-in. Different for static vs dynamic.",
            "What is the purpose of express-rate-limit?": "Rate limiting middleware. Prevent abuse, DDoS. Configure: windowMs, max, message. Store: Memory/Redis. Per IP by default.",
            "How do you handle environment-specific configurations?": "config package or dotenv. NODE_ENV determines file. Development/production settings. Never commit secrets. Validate required vars.",
            "What is the difference between res.redirect() and res.render()?": "redirect(): Sends 302 to new URL. render(): Renders template with data. Use redirect for navigation, render for pages.",
            "How do you implement request timeout handling?": "connect-timeout middleware. Set timeout limit. Handle timeouts gracefully. Return 504 or 408. Cleanup resources.",
            "What is the purpose of body-parser alternatives in modern Express?": "Express 4.16+ has built-in express.json(), express.urlencoded(). No need for separate body-parser. Same functionality.",
        },
        hard: {
            "How do you optimize Express.js application performance?": "Compression, caching, clustering, connection pool, avoid sync code, optimize middleware order, response time monitoring, CDN.",
            "How do you implement advanced security measures in Express.js?": "Helmet, HTTPS, input validation, rate limiting, CSRF protection, secure cookies, audit logs, dependency scanning, penetration testing.",
            "What is the difference between clustering and load balancing?": "Clustering: Multiple Node processes on same server. Load balancing: Distribute across multiple servers. Use both for scale.",
            "How do you implement graceful shutdown in Express.js applications?": "Handle SIGTERM. Stop accepting. Finish pending requests. Close DB connections. Exit. Timeout for stuck requests.",
            "What is the purpose of reverse proxy with Express.js?": "Nginx/Caddy handles: SSL, static files, compression, caching, load balancing. Express handles: API logic. Better security.",
            "How do you handle memory management in Express.js?": "Monitor heap usage. Avoid memory leaks. Limit request body size. Stream large responses. Profile with clinic.js.",
            "What is the difference between horizontal and vertical scaling strategies?": "Vertical: Bigger server. Horizontal: More servers with load balancer. Horizontal preferred. Stateless app required.",
            "How do you implement distributed session management?": "Store sessions in Redis/database. Share across instances. Session affinity optional. Handle failover. TTL for cleanup.",
            "What is the purpose of health check endpoints?": "/health endpoint returns status. Used by load balancers, orchestrators. Check dependencies. Return 200 or 503.",
            "How do you implement advanced logging and monitoring?": "Structured logs (JSON). Log levels. Correlation IDs. APM tools (DataDog, NewRelic). Centralized logging (ELK).",
            "What is the difference between stateless and stateful authentication?": "Stateless: JWT, no server storage. Stateful: Sessions stored server-side. Stateless scales better. Stateful more secure revocation.",
            "How do you handle database connection pooling?": "Configure pool size. Reuse connections. Handle timeouts. Monitor active connections. Pool per database. Close on shutdown.",
            "What is the purpose of circuit breaker pattern in Express.js?": "Prevent cascade failures. Track service failures. Open circuit to fail fast. Gradually recover. opossum library.",
            "How do you implement API gateway functionality?": "Route to microservices. Authentication. Rate limiting. Request transformation. Response aggregation. Kong, AWS API Gateway, or custom.",
            "What is the difference between microservices and monolithic architecture?": "Monolithic: Single app, easier development. Microservices: Separate services, independent scaling. Trade-off complexity.",
            "How do you handle distributed tracing in Express.js?": "OpenTelemetry. Trace ID in headers. Log correlation. Jaeger/Zipkin for visualization. Essential for microservices.",
            "What is the purpose of container orchestration for Express.js apps?": "Kubernetes manages containers. Auto-scaling. Self-healing. Rolling updates. Service discovery. Load balancing.",
            "How do you implement advanced caching strategies?": "Multi-layer: CDN, Redis, in-memory. Cache invalidation strategy. Cache headers. Vary header. Cache key design.",
            "What is the difference between blue-green and rolling deployments?": "Blue-green: Two environments, instant switch. Rolling: Gradual replacement. Blue-green for instant rollback.",
            "How do you handle database migrations in production environments?": "Migration tools. Version control. Test first. Backup. Rollback plan. Zero-downtime (backward compatible).",
            "What is the purpose of service mesh in microservices?": "Istio, Linkerd. Handles: mTLS, load balancing, observability. Sidecar proxy pattern. Infrastructure layer.",
            "How do you implement event-driven architecture with Express.js?": "Emit events to queue (Kafka, RabbitMQ). Async processing. Loose coupling. Event sourcing. CQRS pattern.",
            "What is the difference between synchronous and asynchronous communication?": "Sync: Request-response, waits. Async: Fire-and-forget, queue-based. Async for long operations, loose coupling.",
            "How do you handle eventual consistency in distributed systems?": "Accept delays. Saga pattern. Compensating transactions. Idempotent operations. UI patterns for consistency.",
            "What is the purpose of message queues in Express.js applications?": "Decouple services. Handle spikes. Retry failed jobs. Async processing. RabbitMQ, Redis, AWS SQS.",
        }
    },
    mongodb: {
        easy: {
            "What is MongoDB and what are its key features?": "MongoDB: NoSQL document database. Features: Flexible schema, horizontal scaling, JSON-like documents, indexing, aggregation. Used for modern applications.",
            "What is the difference between SQL and NoSQL databases?": "SQL: Structured, tables, joins, ACID. NoSQL: Flexible schema, documents/key-value, horizontal scaling. Choose based on data model and requirements.",
            "What is a document in MongoDB?": "Document: JSON-like data structure (BSON). Contains field-value pairs. Nested objects, arrays allowed. _id field unique identifier.",
            "What is a collection in MongoDB?": "Collection: Group of documents (like SQL table). No enforced schema. Documents in collection can differ. Created on first insert.",
            "What is BSON and how is it different from JSON?": "BSON: Binary JSON. More data types (Date, ObjectId, Binary). More efficient encoding. MongoDB's internal format.",
            "How do you create a database in MongoDB?": "use databaseName. Database created when first document inserted. show dbs to list. db for current database.",
            "How do you insert documents in MongoDB?": "insertOne({doc}), insertMany([docs]). Returns inserted ID(s). Acknowledged response. Creates collection if not exists.",
            "How do you query documents in MongoDB?": "find({query}), findOne({query}). Query operators: $gt, $lt, $in, $and, $or. Projection for specific fields.",
            "What is the _id field in MongoDB?": "_id: Unique identifier for documents. Auto-generated ObjectId if not provided. Indexed by default. 12-byte unique value.",
            "How do you update documents in MongoDB?": "updateOne/updateMany({filter}, {$set: {}}). $set, $inc, $push, $pull operators. upsert option creates if not exists.",
            "How do you delete documents in MongoDB?": "deleteOne({filter}), deleteMany({filter}). drop() removes collection. Cannot undo. Careful with empty filter.",
            "What is the difference between find() and findOne()?": "find(): Returns cursor for all matches. findOne(): Returns first match only. Use findOne for single document lookup.",
            "What are the basic data types in MongoDB?": "String, Number, Boolean, Date, ObjectId, Array, Object, Binary, Null. BSON supports more types than JSON.",
            "How do you create an index in MongoDB?": "createIndex({field: 1}). 1 for ascending, -1 descending. Compound indexes. Options: unique, sparse, TTL.",
            "What is the purpose of ObjectId in MongoDB?": "ObjectId: 12-byte unique identifier. Contains timestamp, machine ID, process ID, counter. Sortable by creation time.",
            "How do you sort documents in MongoDB?": "find().sort({field: 1}). 1 ascending, -1 descending. Multiple fields. With limit for top-N queries.",
            "What is the limit() method in MongoDB?": "limit(n): Return only n documents. With skip() for pagination. With sort() for ordered results.",
            "How do you count documents in MongoDB?": "countDocuments({filter}). estimatedDocumentCount() faster for total. count() deprecated.",
            "What is the difference between drop() and remove()?": "drop(): Removes entire collection. remove({})/deleteMany({}): Removes documents. drop() faster, clears indexes too.",
            "How do you create a collection in MongoDB?": "createCollection('name', options). Or implicitly on first insert. Options: capped, size, validator.",
            "What is the purpose of pretty() method?": "pretty(): Formats output for readability. Adds indentation. For shell debugging. Not for application code.",
            "How do you check if a database exists in MongoDB?": "show dbs lists databases. Database appears after first document inserted. db.stats() for database info.",
            "What is the difference between save() and insert()?": "save(): Update if _id exists, insert otherwise. insert(): Always insert. save() deprecated, use insertOne/updateOne.",
            "How do you handle arrays in MongoDB documents?": "Arrays are native type. Query: $elemMatch, $all, $size. Update: $push, $pull, $addToSet, $pop. Dot notation for nested.",
            "What is the purpose of explain() method?": "explain(): Shows query execution plan. Modes: queryPlanner, executionStats, allPlansExecution. For optimization.",
        },
        medium: {
            "What is indexing in MongoDB and why is it important?": "Indexes speed up queries. B-tree structure. Without index, scans all documents. Types: Single, Compound, Text, Geospatial. Trade-off: Write performance.",
            "How do you implement aggregation in MongoDB?": "aggregate([stages]). Stages: $match, $group, $project, $sort, $lookup. Pipeline processes documents. Powerful data transformation.",
            "What is the difference between embedded and referenced documents?": "Embedded: Nested documents, single read, duplication. Referenced: ObjectId links, joins ($lookup), normalized. Choose based on access patterns.",
            "How do you implement pagination in MongoDB?": "skip(n) and limit(n). Better: Range-based with _id. skip() performance degrades with large offsets.",
            "What are compound indexes and when to use them?": "Multiple fields in one index. Order matters. Supports prefix queries. Use for queries on multiple fields together.",
            "How do you implement text search in MongoDB?": "Text index on field(s). $text, $search operator. Supports stemming, stop words. Atlas Search for advanced.",
            "What is the purpose of MongoDB Atlas?": "Atlas: Managed MongoDB cloud service. Features: Auto-scaling, backups, monitoring, security. Multi-cloud deployment.",
            "How do you implement data validation in MongoDB?": "Schema validation with $jsonSchema. Validation level: strict, moderate. Apply to collection. Reject invalid documents.",
            "What is the difference between replica set and sharding?": "Replica set: High availability, data copies. Sharding: Horizontal scaling, distribute data. Often used together.",
            "How do you handle transactions in MongoDB?": "startSession(), startTransaction(). ACID across documents. commit/abort. Replica set required. Use for multi-document operations.",
            "What is the purpose of GridFS in MongoDB?": "GridFS: Store files >16MB. Chunks and metadata. fs.files, fs.chunks collections. Streaming support.",
            "How do you implement geospatial queries in MongoDB?": "2dsphere or 2d index. GeoJSON format. $near, $geoWithin, $geoIntersects. For location-based queries.",
            "What is the difference between $lookup and populate?": "$lookup: MongoDB aggregation, server-side join. populate: Mongoose method, multiple queries. $lookup more efficient.",
            "How do you optimize MongoDB queries?": "Proper indexes, covered queries, projection, limit, explain() analysis. Avoid $where, regex starts. Index selectivity.",
            "What is the purpose of MongoDB Compass?": "Compass: GUI for MongoDB. Query, analyze, visualize. Schema analysis. Index suggestions. Aggregation builder.",
            "How do you implement backup and restore in MongoDB?": "mongodump/mongorestore for logical. Cloud snapshots for Atlas. Oplog for point-in-time. Regular automated backups.",
            "What is the difference between $match and $filter?": "$match: Filter documents in pipeline. $filter: Filter array elements within document. Different scopes.",
            "How do you handle large datasets in MongoDB?": "Sharding, proper indexes, covered queries, projection, pagination. Aggregation with $match early. Background tasks.",
            "What is the purpose of change streams in MongoDB?": "Change streams: Real-time data changes. Watch collection/database/deployment. resumeToken for reliability. Event-driven apps.",
            "How do you implement data modeling in MongoDB?": "Consider: Query patterns, read/write ratio, relationships. Embed for 1:1, reference for many. Pattern: Extended reference, subset.",
            "What is the difference between $group and $project?": "$group: Aggregate by field, create new documents. $project: Reshape individual documents, include/exclude fields.",
            "How do you handle concurrent operations in MongoDB?": "Document-level locking. Optimistic concurrency with version field. Transactions for multi-document. findOneAndUpdate atomic.",
            "What is the purpose of MongoDB profiler?": "Profiler logs slow queries. Levels: 0 off, 1 slow, 2 all. system.profile collection. Set slowms threshold.",
            "How do you implement schema design patterns?": "Patterns: Bucket, Computed, Extended Reference, Outlier, Subset. Choose based on query patterns and data characteristics.",
            "What is the difference between $push and $addToSet?": "$push: Always adds to array (allows duplicates). $addToSet: Adds only if unique. Use $addToSet for unique lists.",
        },
        hard: {
            "How do you implement sharding in MongoDB?": "Shard key determines distribution. Config servers store metadata. Mongos routes queries. Enable sharding on database, collection.",
            "What is the difference between horizontal and vertical scaling in MongoDB?": "Vertical: Bigger server (limited). Horizontal: Sharding across servers. MongoDB designed for horizontal scaling.",
            "How do you optimize MongoDB performance for large datasets?": "Sharding, proper shard key, zone sharding, indexes, aggregation optimization, covered queries, hardware (SSD, RAM).",
            "What is the purpose of replica sets and how do they work?": "Replica set: Primary + secondaries. Automatic failover. Data replication. Read preferences. Election process.",
            "How do you implement distributed transactions in MongoDB?": "Multi-document transactions across shards. Session-based. Coordinator in sharded. Performance impact. Use sparingly.",
            "What is the difference between read and write concerns?": "Write concern: Acknowledgment level (w: majority). Read concern: Data recency guarantee. Trade-off between consistency and performance.",
            "How do you handle data consistency in MongoDB clusters?": "Write concern: majority. Read concern: majority/linearizable. Causal consistency for sessions. Trade-off with latency.",
            "What is the purpose of MongoDB oplog?": "Oplog (operations log): Capped collection of all write operations. Used for replication, change streams. In local database.",
            "How do you implement advanced aggregation pipelines?": "Complex: $facet, $graphLookup, $merge, $out. Optimize: $match early, $project after $lookup. Memory limit for large.",
            "What is the difference between primary and secondary nodes?": "Primary: Accepts writes, one per replica set. Secondary: Read replicas, can become primary. Arbiter: Voting only.",
            "How do you handle failover in MongoDB replica sets?": "Automatic election when primary fails. Majority needed for election. Application reconnects. rs.status() to monitor.",
            "What is the purpose of MongoDB balancer?": "Balancer distributes chunks across shards. Runs in background. Can schedule windows. Balance threshold configurable.",
            "How do you implement advanced indexing strategies?": "Partial indexes, wildcard indexes, hidden indexes, TTL indexes. Index intersection. Analyze with explain().",
            "What is the difference between covered and non-covered queries?": "Covered query: All fields in index, no document fetch. Much faster. Check with explain(). Return only indexed fields.",
            "How do you handle memory management in MongoDB?": "WiredTiger cache (50% RAM). Working set in memory. Index RAM requirements. Monitor with serverStatus().",
            "What is the purpose of MongoDB WiredTiger storage engine?": "WiredTiger: Default engine. Compression, document-level locking, checkpoint, journal. Configurable cache size.",
            "How do you implement advanced security measures?": "Authentication, RBAC, TLS/SSL, network encryption, field-level encryption, auditing. SCRAM-SHA-256. IP whitelisting.",
            "What is the difference between authentication and authorization?": "Authentication: Verify identity (username/password). Authorization: What user can do (roles, privileges). Both required.",
            "How do you handle database migrations in MongoDB?": "Schema versioning, migration scripts, gradual rollout. No DDL like SQL. Application handles schema evolution.",
            "What is the purpose of MongoDB change streams for real-time applications?": "Watch for changes. Build reactive apps. Resume after disconnect. Aggregate on changes. Replace polling.",
            "How do you implement advanced monitoring and alerting?": "MongoDB Atlas monitoring, Prometheus/Grafana, Cloud Manager. Alert on: Replication lag, disk space, connections.",
            "What is the difference between ACID and BASE properties?": "ACID: Atomicity, Consistency, Isolation, Durability. BASE: Basically Available, Soft state, Eventually consistent. Trade-offs.",
            "How do you handle eventual consistency in distributed MongoDB?": "Read/write concerns, causal consistency, design for eventual. Compensating transactions. Idempotent operations.",
            "What is the purpose of MongoDB time series collections?": "Time series: Optimized for temporal data. Automatic bucketing. Compression. Meta and time fields. IoT, metrics.",
            "How do you implement advanced backup and disaster recovery strategies?": "Continuous backup, point-in-time recovery, cross-region replication. RTO/RPO planning. Disaster recovery testing.",
        }
    },
    python: {
        easy: {
            "What is Python and what are its key features?": "Python: High-level, interpreted language. Features: Readable syntax, dynamic typing, garbage collection, extensive libraries. Used for web, data science, automation.",
            "What is the difference between Python 2 and Python 3?": "Python 3: print() function, integer division, Unicode default, range() returns iterator. Python 2 end of life 2020. Always use Python 3.",
            "What are the basic data types in Python?": "Primitives: int, float, str, bool, None. Collections: list, tuple, dict, set. type() to check. Everything is object.",
            "What is the difference between list and tuple?": "List: Mutable, square brackets []. Tuple: Immutable, parentheses (). Tuple faster, hashable. Use tuple for fixed data.",
            "What is a dictionary in Python?": "Dict: Key-value pairs. {key: value}. Keys unique, hashable. Access: dict[key]. Methods: get(), keys(), values(), items().",
            "What is the difference between append() and extend()?": "append(): Add single element to end. extend(): Add all elements from iterable. append adds one, extend merges.",
            "What is list comprehension in Python?": "Concise list creation: [x*2 for x in range(10) if x > 5]. Readable, Pythonic. Dict/set comprehensions too.",
            "What is the difference between == and is operators?": "==: Value equality. is: Identity (same object). Use == for values, is for None checking. Careful with caching.",
            "What is the purpose of __init__ method?": "__init__: Constructor, initializes instance. Called after __new__. self refers to instance. Initialize attributes here.",
            "What is the difference between local and global variables?": "Local: Defined in function, scoped to function. Global: Defined outside, accessible everywhere. Use global keyword to modify.",
            "What is exception handling in Python?": "try/except/finally blocks. Catch specific exceptions first. Raise exceptions. Custom exception classes. Don't catch bare except.",
            "What is the purpose of try-except blocks?": "Handle errors gracefully. try: risky code. except: handle error. else: no error. finally: always runs. Catch specific exceptions.",
            "What is the difference between break and continue?": "break: Exit loop entirely. continue: Skip to next iteration. In nested loops, affects innermost. Use else clause for no-break.",
            "What is a lambda function in Python?": "Anonymous function: lambda x: x*2. Single expression. Used in map(), filter(), sorted(). Limited, prefer def for complex.",
            "What is the purpose of *args and **kwargs?": "*args: Variable positional arguments (tuple). **kwargs: Variable keyword arguments (dict). Flexible function signatures.",
            "What is the difference between shallow and deep copy?": "Shallow: New object, same nested references. Deep: Completely independent copy. import copy; copy.copy() vs copy.deepcopy().",
            "What is the purpose of enumerate() function?": "enumerate(): Returns (index, value) pairs. for i, val in enumerate(list). Start index configurable. Pythonic iteration.",
            "What is the difference between range() and xrange()?": "Python 3: Only range() (lazy iterator). Python 2: range() list, xrange() iterator. Always use range() in Python 3.",
            "What is the purpose of zip() function?": "zip(): Combine iterables pairwise. Returns iterator. Unzip with zip(*pairs). Truncates to shortest. zip_longest for padding.",
            "What is the difference between remove() and pop()?": "remove(value): Remove first occurrence by value. pop(index): Remove and return by index. del for slice removal.",
            "What is string formatting in Python?": "f-strings: f'{name}'. format(): '{}'.format(x). %-formatting: '%s' % x. f-strings preferred (3.6+), readable.",
            "What is the purpose of join() method?": "join(): Combine iterable into string. separator.join(list). Opposite of split(). More efficient than concatenation.",
            "What is the difference between split() and partition()?": "split(): Split by separator into list. partition(): Split into 3 parts (before, sep, after). split() multiple, partition() once.",
            "What is the purpose of map() function?": "map(func, iterable): Apply function to each element. Returns iterator. Alternative: List comprehension. Lazy evaluation.",
            "What is the difference between filter() and reduce()?": "filter(): Keep elements where function is True. reduce(): Combine elements (functools). Filter for selection, reduce for aggregation.",
        },
        medium: {
            "What are decorators in Python and how do they work?": "Decorator: Function that modifies another function. @decorator syntax. Takes function, returns wrapped. Used for logging, auth, caching.",
            "What is the difference between classmethod and staticmethod?": "classmethod: Receives class as first argument (cls). staticmethod: No implicit argument. classmethod for factory methods.",
            "What are generators in Python and how do they work?": "Generators: Lazy iterators using yield. Memory efficient. next() to iterate. Generator expressions. For large sequences.",
            "What is the purpose of yield keyword?": "yield: Pause function, return value, resume later. Creates generator. Saves state between calls. Lazy evaluation.",
            "What is multiple inheritance in Python?": "Class inherits from multiple parents. class C(A, B). Diamond problem handled by MRO. Use super() properly.",
            "What is the Method Resolution Order (MRO)?": "MRO: Order Python searches for methods. C3 linearization. ClassName.__mro__ to see. super() follows MRO.",
            "What are context managers in Python?": "with statement: Setup and cleanup. __enter__ and __exit__ methods. Or contextlib.contextmanager decorator. For resources.",
            "What is the purpose of __enter__ and __exit__ methods?": "__enter__: Setup, return context object. __exit__: Cleanup, handle exceptions. Exception info passed to __exit__.",
            "What is the difference between __str__ and __repr__?": "__str__: Human-readable string. __repr__: Unambiguous representation (for developers). repr() in debugger, str() for users.",
            "What are metaclasses in Python?": "Metaclass: Class of a class. type is default. Controls class creation. Use for: ORM, API frameworks. Advanced feature.",
            "What is the purpose of property decorator?": "@property: Make method act like attribute. Getter, setter, deleter. Encapsulation. Computed attributes.",
            "What is the difference between instance and class variables?": "Instance: Per object (self.attr). Class: Shared across instances (Class.attr). Define class vars in class body.",
            "What is duck typing in Python?": "Duck typing: If it walks like a duck... Type checked by behavior, not class. Enables polymorphism. EAFP over LBYL.",
            "What is the purpose of __slots__?": "__slots__: Memory optimization. Define allowed attributes. No __dict__. Faster attribute access. Use for many instances.",
            "What is the difference between pickle and json?": "pickle: Python-specific, any object, binary. json: Language-agnostic, limited types, human-readable. json for APIs.",
            "What are regular expressions in Python?": "re module: Pattern matching. re.match(), search(), findall(), sub(). Compile for reuse. Raw strings r'pattern'.",
            "What is the purpose of collections module?": "collections: Specialized containers. namedtuple, deque, Counter, defaultdict, OrderedDict. Useful data structures.",
            "What is the difference between threading and multiprocessing?": "Threading: Shared memory, GIL limits CPU. Multiprocessing: Separate memory, true parallelism. Thread for I/O, process for CPU.",
            "What is the Global Interpreter Lock (GIL)?": "GIL: Only one thread executes Python bytecode. Limits CPU parallelism. Multiprocessing bypasses. I/O releases GIL.",
            "What is the purpose of asyncio in Python?": "asyncio: Async I/O framework. async/await syntax. Event loop. Concurrent I/O without threads. For I/O-bound tasks.",
            "What is the difference between coroutines and generators?": "Generator: yield values. Coroutine: await other coroutines. async def for coroutines. Coroutines for async I/O.",
            "What is the purpose of virtual environments?": "venv: Isolated Python environments. Separate dependencies per project. python -m venv env. Activate to use.",
            "What is the difference between pip and conda?": "pip: Python packages from PyPI. conda: Any language, binary packages, environment management. Use pip in venv typically.",
            "What is the purpose of requirements.txt?": "requirements.txt: List project dependencies. pip freeze > requirements.txt. pip install -r requirements.txt. Version pinning.",
            "What is the difference between unittest and pytest?": "unittest: Built-in, class-based, verbose. pytest: Simpler, fixtures, plugins, better output. pytest more popular.",
        },
        hard: {
            "How do you optimize Python code performance?": "Profile first (cProfile). Use built-ins, list comprehensions, generators. Numpy for arrays. Cache. Cython for bottlenecks.",
            "What is the difference between CPython, PyPy, and Jython?": "CPython: Reference implementation, C. PyPy: JIT compilation, faster. Jython: Java platform. CPython default.",
            "How do you implement design patterns in Python?": "Singleton, Factory, Observer, Decorator, Strategy. Pythonic variations. Often simpler than Java. Modules as singletons.",
            "What is the purpose of memory profiling in Python?": "memory_profiler, tracemalloc: Find memory usage. Identify bloat. Optimize data structures. Important for data processing.",
            "How do you handle large datasets efficiently in Python?": "Generators, chunking, numpy/pandas. Memory-mapped files. Dask for parallel. Database for very large. Don't load all at once.",
            "What is the difference between synchronous and asynchronous programming?": "Sync: Sequential execution. Async: Concurrent without threads (asyncio). Async for I/O-bound. await for coroutines.",
            "How do you implement concurrent programming in Python?": "Threading for I/O, multiprocessing for CPU, asyncio for async I/O. concurrent.futures for high-level API.",
            "What is the purpose of Cython for performance optimization?": "Cython: Python with C types. Compile to C extension. 10-100x speedup. For computational bottlenecks.",
            "How do you implement distributed computing with Python?": "Celery for tasks, Dask for data, Ray for ML, PySpark for big data. Message queues. microservices.",
            "What is the difference between weak and strong references?": "Strong: Prevents garbage collection. Weak (weakref): Allows collection. Use weak for caches to avoid memory leaks.",
            "How do you handle memory management in Python?": "Automatic garbage collection. Reference counting + cycle detection. del to hint. __del__ for cleanup. Avoid circular refs.",
            "What is the purpose of garbage collection in Python?": "GC reclaims unused memory. Reference counting + generational collector for cycles. gc module to control. Automatic.",
            "How do you implement custom iterators and iterables?": "__iter__ returns iterator. __next__ returns next value, raises StopIteration. Or use generator (yield).",
            "What is the difference between composition and inheritance?": "Inheritance: Is-a relationship. Composition: Has-a, contains objects. Prefer composition, more flexible. Avoid deep hierarchies.",
            "How do you implement advanced exception handling strategies?": "Custom exceptions, exception chaining, context managers, logging exceptions, re-raising, exception groups (3.11).",
            "What is the purpose of abstract base classes?": "ABC: Define interface. abc module. @abstractmethod. Cannot instantiate. Enforce implementation. Duck typing alternative.",
            "How do you implement thread-safe code in Python?": "threading.Lock, RLock, Condition, Semaphore. Queue for communication. Avoid shared mutable state. GIL helps but not enough.",
            "What is the difference between cooperative and preemptive multitasking?": "Cooperative: Tasks yield voluntarily (asyncio). Preemptive: OS switches (threads). Async simpler reasoning.",
            "How do you implement advanced logging and monitoring?": "logging module: Handlers, formatters, levels. Structured logging. Centralize logs. APM integration. Correlation IDs.",
            "What is the purpose of profiling and benchmarking?": "Profiling: Find slow code (cProfile, line_profiler). Benchmarking: Compare performance (timeit). Profile before optimizing.",
            "How do you handle database connections and connection pooling?": "Connection pools (SQLAlchemy pool, psycopg2 pool). Avoid creating connections per request. Close properly. async pools.",
            "What is the difference between WSGI and ASGI?": "WSGI: Sync web interface. ASGI: Async support (WebSocket, HTTP/2). ASGI for async frameworks (FastAPI).",
            "How do you implement advanced security measures?": "Input validation, parameterized queries, secrets management, dependency scanning, HTTPS, security headers.",
            "What is the purpose of containerization for Python applications?": "Docker: Consistent environments. Reproducible deployments. Kubernetes for orchestration. Multi-stage builds.",
            "How do you implement CI/CD pipelines for Python projects?": "GitHub Actions, GitLab CI. Lint, test, build, deploy. Automated. Staging environments. Version control.",
        }
    },
    django: {
        easy: {
            "What is Django and what are its key features?": "Django: Python web framework. Features: ORM, admin, auth, templates, security. Batteries included. MTV pattern.",
            "What is the MVT pattern in Django?": "Model: Data layer (ORM). View: Business logic. Template: Presentation. Similar to MVC. Django handles controller.",
            "How do you create a Django project?": "django-admin startproject projectname. Creates settings, urls, wsgi. python manage.py runserver to start.",
            "What is the difference between project and app in Django?": "Project: Configuration, settings. App: Feature module, reusable. Project contains apps. INSTALLED_APPS registers apps.",
            "What is a Django model?": "Model: Python class representing database table. Fields define columns. ORM maps to SQL. Migrations handle schema.",
            "How do you create a model in Django?": "class MyModel(models.Model): field = models.CharField(). Define fields, Meta options. Run makemigrations, migrate.",
            "What is migration in Django?": "Migrations: Database schema changes. makemigrations creates, migrate applies. Version controlled. Reversible.",
            "How do you create and apply migrations?": "python manage.py makemigrations, python manage.py migrate. Check with showmigrations. Squash for cleanup.",
            "What is Django admin and how do you use it?": "Admin: Auto-generated CRUD interface. Register models: admin.site.register(Model). Customize with ModelAdmin.",
            "What is a Django view?": "View: Python function/class handling requests. Returns HttpResponse. Access request data. Use render() for templates.",
            "What is the difference between function-based and class-based views?": "FBV: Simple, explicit. CBV: Reusable, inheritance, mixins. CBV for common patterns. FBV for simple logic.",
            "What is URL routing in Django?": "urls.py maps URLs to views. path(), re_path(). Include() for app URLs. Named URLs. URL parameters.",
            "How do you create URL patterns in Django?": "path('route/<int:id>/', view, name='name'). urlpatterns list. Include app patterns. Namespace for apps.",
            "What is a Django template?": "Template: HTML with Django template language. Variables {{}}, tags {% %}. Inheritance, filters. Separation of logic.",
            "What is template inheritance in Django?": "{% extends 'base.html' %}, {% block content %}. Base template with blocks. Children override blocks. DRY templates.",
            "What is the purpose of settings.py?": "settings.py: Project configuration. Database, apps, middleware, templates, static files. Environment-specific settings.",
            "What is the difference between DEBUG=True and DEBUG=False?": "DEBUG=True: Detailed errors, auto-reload. False: Production mode, no sensitive info. Never DEBUG=True in production.",
            "How do you serve static files in Django?": "STATIC_URL, STATICFILES_DIRS. {% load static %}, {% static 'path' %}. collectstatic for production. Use CDN.",
            "What is the purpose of manage.py?": "manage.py: Django command-line utility. runserver, migrate, shell, createsuperuser. Project-specific commands.",
            "How do you create a superuser in Django?": "python manage.py createsuperuser. Admin access. Set username, email, password. Can create programmatically.",
            "What is the difference between CharField and TextField?": "CharField: Limited length (max_length required). TextField: No limit. CharField for short strings, TextField for long text.",
            "What is the purpose of __str__ method in models?": "__str__: String representation. Shown in admin, shell. Return meaningful identifier. Should return string.",
            "How do you handle forms in Django?": "forms.Form or ModelForm. Render in template. Validate with is_valid(). Access cleaned_data. Handle POST.",
            "What is CSRF protection in Django?": "CSRF: Cross-Site Request Forgery protection. {% csrf_token %} in forms. CsrfViewMiddleware. Always use for POST.",
            "What is the purpose of Django ORM?": "ORM: Object-Relational Mapping. Python to SQL. QuerySets. CRUD operations. Database agnostic.",
        },
        medium: {
            "How do you implement authentication in Django?": "Built-in auth: User model, login, logout, decorators. @login_required. Custom user model. Password hashing automatic.",
            "What is the difference between authentication and authorization?": "Authentication: Who is user (login). Authorization: What can user do (permissions). Django has both built-in.",
            "How do you create custom user models in Django?": "AbstractUser or AbstractBaseUser. AUTH_USER_MODEL in settings. Create before first migrate. Custom fields, methods.",
            "What is the purpose of Django middleware?": "Middleware: Process request/response globally. Order matters. Built-in: Auth, CSRF, session. Custom middleware possible.",
            "How do you implement custom middleware?": "Class with __init__, __call__. Process request/response. Use get_response callable. Register in MIDDLEWARE setting.",
            "What is the difference between select_related and prefetch_related?": "select_related: Single query JOIN (ForeignKey). prefetch_related: Separate query (ManyToMany). Optimize N+1 queries.",
            "How do you implement pagination in Django?": "Paginator class. paginator.page(num). Template: page_obj.has_previous/next. ListView has built-in pagination.",
            "What is the purpose of Django signals?": "Signals: Notify on events. pre_save, post_save, etc. Decouple components. @receiver decorator. Careful with side effects.",
            "How do you handle file uploads in Django?": "FileField, ImageField. MEDIA_URL, MEDIA_ROOT. form.save() handles upload. Validate file type and size.",
            "What is the difference between Model.save() and bulk_create()?": "save(): Single object, triggers signals. bulk_create(): Many objects, faster, no signals. Use bulk for performance.",
            "How do you implement caching in Django?": "Cache backends: Memcached, Redis, file. cache.set/get. @cache_page decorator. Template fragment caching. Vary headers.",
            "What is the purpose of Django REST framework?": "DRF: Build REST APIs. Serializers, viewsets, routers, authentication. Browsable API. Standard for Django APIs.",
            "How do you create API endpoints with Django?": "DRF: Serializers for data, Views/ViewSets for logic, Routers for URLs. Response types, status codes.",
            "What is serialization in Django REST framework?": "Serializers: Convert models to JSON and vice versa. Validation. ModelSerializer from model. Nested serializers.",
            "How do you implement validation in Django forms?": "Field validators, clean_<field>(), clean(). Form.is_valid(). Return cleaned_data. Raise ValidationError.",
            "What is the purpose of Django sessions?": "Sessions: Store user data server-side. Session ID in cookie. Database, cached, file backends. request.session dict.",
            "How do you handle database transactions in Django?": "transaction.atomic() decorator/context manager. Rollback on exception. Savepoints. select_for_update() for locking.",
            "What is the difference between Q objects and F objects?": "Q: Complex queries with OR/AND. F: Reference model field in query. F for comparisons against same model fields.",
            "How do you implement custom template tags and filters?": "templatetags/ directory. @register.filter, @register.simple_tag. Load in template. Reusable template logic.",
            "What is the purpose of Django management commands?": "Custom commands: BaseCommand subclass. Run with manage.py. For admin tasks, cron jobs. Handle stdout, style.",
            "How do you implement internationalization in Django?": "USE_I18N, LANGUAGES. {% trans %}, gettext. makemessages, compilemessages. Locale middleware. Date formatting.",
            "What is the difference between render and redirect?": "render(): Return response with template. redirect(): HTTP redirect (302). render for page, redirect for navigation.",
            "How do you handle environment variables in Django?": "python-decouple or django-environ. .env files. os.environ. Never commit secrets. Different per environment.",
            "What is the purpose of Django fixtures?": "Fixtures: Pre-populate database. JSON, YAML format. loaddata/dumpdata. For testing, initial data.",
            "How do you implement testing in Django?": "TestCase class. Client for request simulation. setUp/tearDown. Factories (factory_boy). Coverage. CI integration.",
        },
        hard: {
            "How do you optimize Django application performance?": "select_related/prefetch_related, caching, database indexes, query optimization, async views (4.1+), CDN, compression.",
            "What is the difference between database optimization techniques?": "Indexes, query optimization, connection pooling, read replicas, caching layer. Profile with django-debug-toolbar.",
            "How do you implement advanced caching strategies?": "Multi-level cache, cache invalidation, cache key design, vary headers, template fragment, queryset caching.",
            "What is the purpose of database connection pooling?": "Reuse connections. django-db-connection-pool, PgBouncer. Reduce connection overhead. Essential for performance.",
            "How do you handle large file uploads efficiently?": "Chunked uploads, cloud storage (S3), async processing (Celery), streaming response. Don't store in database.",
            "What is the difference between synchronous and asynchronous views?": "Sync: Traditional. Async (Django 4.1+): async def view. ASGI required. For I/O-bound operations. async ORM in progress.",
            "How do you implement real-time features with Django Channels?": "Channels: WebSocket support. Consumers handle connections. Channel layers (Redis). ASGI. For chat, notifications.",
            "What is the purpose of Celery for background tasks?": "Celery: Distributed task queue. Async task execution. Scheduled tasks (beat). Redis/RabbitMQ broker. For long operations.",
            "How do you implement distributed task queues?": "Celery with multiple workers. Message broker. Task routing. Retries, error handling. Monitoring (Flower).",
            "What is the difference between horizontal and vertical scaling?": "Vertical: Bigger server. Horizontal: Multiple servers, load balancer. Django scales horizontally well.",
            "How do you handle database sharding in Django?": "Database routers, multiple databases. Application-level sharding. Complexity trade-off. Consider when needed.",
            "What is the purpose of load balancing for Django applications?": "Distribute traffic. Nginx, HAProxy, cloud LB. Sticky sessions if needed. Health checks. High availability.",
            "How do you implement advanced security measures?": "HTTPS, security headers, CSRF, XSS protection, SQL injection prevention (ORM), rate limiting, audit logs.",
            "What is the difference between SQL injection and XSS attacks?": "SQL injection: Malicious SQL through input. XSS: Malicious scripts in pages. ORM prevents SQL injection, escape output for XSS.",
            "How do you handle database migrations in production?": "Test migrations first. Backward compatible. Blue-green deployment. Rollback plan. Avoid data loss.",
            "What is the purpose of Django deployment strategies?": "Gunicorn/uWSGI + Nginx. Docker containerization. CI/CD pipeline. Zero-downtime deployment. Environment configuration.",
            "How do you implement monitoring and logging?": "Django logging, Sentry for errors, APM tools (New Relic, DataDog). Structured logs. Centralized logging.",
            "What is the difference between Docker and virtual machines?": "Docker: Containers share OS kernel, lightweight. VMs: Full OS, heavy. Docker preferred for microservices.",
            "How do you implement CI/CD pipelines for Django?": "GitHub Actions, GitLab CI. Lint, test, migrate, deploy. Automated. Staging environment. Rollback capability.",
            "What is the purpose of microservices architecture?": "Independent services, separate databases. API communication. Scale individually. Complexity trade-off.",
            "How do you handle API versioning in Django?": "URL prefix (/api/v1/), header versioning. Separate serializers/views per version. Deprecation strategy.",
            "What is the difference between REST and GraphQL APIs?": "REST: Resources with URLs, multiple endpoints. GraphQL: Single endpoint, client specifies data. Choose based on needs.",
            "How do you implement advanced authentication mechanisms?": "JWT, OAuth2/OIDC, social auth (django-allauth), MFA. Token refresh. Secure token storage.",
            "What is the purpose of containerization for Django apps?": "Docker: Consistent environments. Reproducible builds. Kubernetes for orchestration. Multi-stage builds.",
            "How do you handle eventual consistency in distributed systems?": "Accept delays, saga pattern, event sourcing, CQRS. Design for consistency. Compensating transactions.",
        }
    },
    fastapi: {
        easy: {
            "What is FastAPI and what are its key features?": "FastAPI: Modern Python web framework. Features: Fast (Starlette + Pydantic), type hints, auto docs, async support. For APIs.",
            "How do you create a basic FastAPI application?": "from fastapi import FastAPI; app = FastAPI(); @app.get('/') def read_root(): return {'Hello': 'World'}. Run with uvicorn.",
            "What is the difference between FastAPI and Flask?": "FastAPI: Async, type hints, auto validation, auto docs. Flask: Synchronous, lighter, more manual. FastAPI more modern.",
            "How do you define path parameters in FastAPI?": "@app.get('/items/{item_id}'). Access in function: item_id: int. Type conversion automatic. Validation included.",
            "What are query parameters in FastAPI?": "Parameters not in path: ?skip=0&limit=10. Function params: skip: int = 0. Optional with default. Validated.",
            "How do you handle request body in FastAPI?": "Pydantic model as parameter type. Automatic validation. item: Item. Access item.name. JSON parsing automatic.",
            "What is Pydantic and how is it used in FastAPI?": "Pydantic: Data validation using Python types. BaseModel defines schema. Automatic JSON conversion. Validation errors structured.",
            "How do you create API documentation in FastAPI?": "Auto-generated at /docs (Swagger) and /redoc. From type hints and docstrings. Customize with metadata.",
            "What is the purpose of @app.get() decorator?": "@app.get(): Handle GET requests. Also: post, put, delete, patch. Response model, status code configurable.",
            "How do you handle different HTTP methods in FastAPI?": "@app.get(), @app.post(), @app.put(), @app.delete(), @app.patch(). Each for specific HTTP method.",
            "What is type hinting in FastAPI?": "Type hints define parameter and return types. Used for: Validation, documentation, editor support. Core to FastAPI.",
            "How do you validate request data in FastAPI?": "Pydantic models with Field(). Path(), Query() with constraints. Automatic 422 response on validation error.",
            "What is the difference between Path and Query?": "Path: URL path parameters (/items/{id}). Query: URL query parameters (?skip=0). Both validate and document.",
            "How do you handle file uploads in FastAPI?": "from fastapi import File, UploadFile. file: UploadFile = File(...). Access file.filename, await file.read().",
            "What is the purpose of Response model?": "response_model: Define response schema. Filters output. Documentation. Type safety. Pydantic model.",
            "How do you handle errors in FastAPI?": "HTTPException: raise HTTPException(status_code=404). Custom exception handlers. Validation errors automatic.",
            "What is the difference between synchronous and asynchronous endpoints?": "async def: Non-blocking, for I/O operations. def: Runs in thread pool. Use async for I/O-bound.",
            "How do you serve static files in FastAPI?": "StaticFiles: from fastapi.staticfiles import StaticFiles. app.mount('/static', StaticFiles(directory='static')).",
            "What is the purpose of status codes in FastAPI?": "status_code parameter: Default status. status module for constants. Return appropriate HTTP codes.",
            "How do you create custom response models?": "Pydantic model for response_model. Define fields, types. Config for customization. Nested models.",
            "What is the difference between POST and PUT methods?": "POST: Create resource. PUT: Replace/update resource. PUT idempotent. Use appropriately.",
            "How do you handle cookies in FastAPI?": "Response.set_cookie(), Cookie() for reading. from fastapi import Cookie. Access: cookie_name: str = Cookie().",
            "What is the purpose of Header parameters?": "Header(): Read request headers. header_name: str = Header(). Automatic conversion of underscores to hyphens.",
            "How do you implement basic authentication?": "HTTPBasic from fastapi.security. Verify credentials. Return 401 if failed. HTTPBasicCredentials model.",
            "What is the difference between Form and Body?": "Form: URL-encoded form data. Body: JSON body. UploadFile with Form for files. Different content types.",
        },
        medium: {
            "How do you implement JWT authentication in FastAPI?": "python-jose for JWT. Create token with encode(). Verify with decode(). OAuth2PasswordBearer for token endpoint.",
            "What is dependency injection in FastAPI?": "Depends(): Inject dependencies. Reusable components. Database sessions, auth. Automatic handling. Sub-dependencies.",
            "How do you create reusable dependencies?": "def get_db(): yield db. Depends(get_db) in route. Cleanup with yield. Nested dependencies compose.",
            "What is the purpose of middleware in FastAPI?": "Middleware: Process request/response. CORS, timing, logging. @app.middleware('http'). Or Starlette middleware.",
            "How do you implement CORS in FastAPI?": "CORSMiddleware: from fastapi.middleware.cors. Configure: origins, methods, headers. Allow credentials option.",
            "What is the difference between BackgroundTasks and Celery?": "BackgroundTasks: Simple, same process. Celery: Distributed, persistent, complex. BackgroundTasks for simple async.",
            "How do you handle database integration with FastAPI?": "SQLAlchemy recommended. Dependency for session. Async with databases library. Tortoise-ORM alternative.",
            "What is SQLAlchemy and how do you use it with FastAPI?": "SQLAlchemy: Python ORM. Define models, sessionmaker. Depends() for session injection. Async SQLAlchemy available.",
            "How do you implement pagination in FastAPI?": "Skip and limit query params. skip: int = 0, limit: int = 10. Calculate offset. Return total count.",
            "What is the purpose of response models and serialization?": "response_model: Controls output. Exclude fields. Multiple response for status codes. Pydantic serialization.",
            "How do you handle validation errors in FastAPI?": "RequestValidationError handler. Custom error response. Add exception handler. Structured error messages.",
            "What is the difference between Field and Body validation?": "Field: Model field validation. Body: Request body validation with metadata. Both for constraints.",
            "How do you implement rate limiting in FastAPI?": "slowapi library. @limiter.limit('10/minute'). Redis backend for distributed. Custom key function.",
            "What is the purpose of OpenAPI schema generation?": "Automatic OpenAPI spec. /openapi.json endpoint. For documentation, client generation. Customize with metadata.",
            "How do you customize API documentation?": "FastAPI metadata: title, description, version. Tags organize endpoints. Docstrings for descriptions.",
            "What is the difference between sync and async database operations?": "Sync: Traditional SQLAlchemy, runs in thread. Async: databases library, non-blocking. Async for high concurrency.",
            "How do you implement caching in FastAPI?": "fastapi-cache library. Redis backend. @cache() decorator. TTL configuration. Key customization.",
            "What is the purpose of WebSocket support in FastAPI?": "WebSocket: Real-time bidirectional. @app.websocket(). accept, receive, send. For chat, live updates.",
            "How do you handle environment configuration?": "pydantic BaseSettings. Reads from environment, .env. Type validation. Nested configuration. Easy testing.",
            "What is the difference between testing sync and async endpoints?": "TestClient for sync. pytest-asyncio for async. httpx.AsyncClient. Both work with FastAPI.",
            "How do you implement logging in FastAPI?": "Python logging module. Middleware for request logging. Structured logs. uvicorn logging configuration.",
            "What is the purpose of security utilities in FastAPI?": "OAuth2PasswordBearer, HTTPBasic, APIKeyHeader. Security schemes for OpenAPI. Handle authentication.",
            "How do you handle large file uploads efficiently?": "UploadFile: Spooled to disk. Stream reading. Cloud storage (S3). Background processing.",
            "What is the difference between OAuth2 and JWT?": "OAuth2: Authorization framework, flows. JWT: Token format. OAuth2 can use JWT. JWT for stateless auth.",
            "How do you implement API versioning in FastAPI?": "URL prefix with routers: /v1/, /v2/. Or header-based. APIRouter for organization. Version per router.",
        },
        hard: {
            "How do you optimize FastAPI application performance?": "Async operations, connection pooling, caching, CDN, profiling. Uvicorn workers. Database optimization.",
            "What is the difference between ASGI and WSGI servers?": "WSGI: Sync (gunicorn). ASGI: Async support (uvicorn, hypercorn). FastAPI requires ASGI.",
            "How do you implement advanced authentication and authorization?": "OAuth2 flows, permissions dependencies, role-based access. Custom authentication backends. Token refresh.",
            "What is the purpose of custom middleware for performance monitoring?": "Request timing, memory usage. Prometheus metrics. APM integration. Custom headers for tracing.",
            "How do you handle database connection pooling?": "SQLAlchemy pool configuration. Async: databases pool. Size limits. Connection health checks.",
            "What is the difference between horizontal and vertical scaling strategies?": "Vertical: More resources. Horizontal: More instances. FastAPI scales horizontally. Stateless design.",
            "How do you implement distributed caching with Redis?": "aioredis for async. Cache layer dependency. TTL management. Cache invalidation. Cluster support.",
            "What is the purpose of message queues in FastAPI applications?": "Celery, aio-pika for RabbitMQ. Async task processing. Decouple services. Handle spikes.",
            "How do you handle graceful shutdown and health checks?": "Lifespan events for cleanup. /health endpoint. Kubernetes probes. Connection draining.",
            "What is the difference between microservices and monolithic architecture?": "Monolithic: Single app. Microservices: Separate services. FastAPI good for both. Choose based on needs.",
            "How do you implement advanced security measures?": "HTTPS, rate limiting, input validation, CORS, authentication. Security headers. Dependency scanning.",
            "What is the purpose of API gateway patterns?": "Central entry point. Authentication, rate limiting, routing. Kong, AWS API Gateway, or custom.",
            "How do you handle distributed tracing and monitoring?": "OpenTelemetry integration. Correlation IDs. Jaeger/Zipkin. APM tools. Structured logging.",
            "What is the difference between event-driven and request-response patterns?": "Request-response: Sync call. Event-driven: Async, decoupled. Events with Kafka, RabbitMQ.",
            "How do you implement advanced testing strategies?": "Unit, integration, e2e tests. pytest fixtures. Async testing. Mocking dependencies. Coverage.",
            "What is the purpose of containerization and orchestration?": "Docker for consistency. Kubernetes for orchestration. Scaling, health checks. CI/CD integration.",
            "How do you handle database migrations in production?": "Alembic for migrations. Version control. Test first. Zero-downtime strategies. Rollback plan.",
            "What is the difference between blue-green and canary deployments?": "Blue-green: Switch environments. Canary: Gradual rollout. Both reduce risk. Kubernetes supports.",
            "How do you implement advanced logging and observability?": "Structured logging (JSON). Centralized (ELK). Metrics (Prometheus). Tracing. Dashboards.",
            "What is the purpose of circuit breaker patterns?": "Prevent cascade failures. Track failures. Open circuit. Recovery. Libraries: aiobreaker.",
            "How do you handle eventual consistency in distributed systems?": "Design for it. Saga pattern. Idempotent operations. Event sourcing. Compensating transactions.",
            "What is the difference between synchronous and asynchronous communication?": "Sync: Wait for response. Async: Message queues. Async for decoupling, resilience.",
            "How do you implement advanced caching strategies?": "Multi-layer: CDN, Redis, local. Cache invalidation. Vary headers. TTL strategy.",
            "What is the purpose of service mesh in microservices?": "Istio, Linkerd. mTLS, load balancing, observability. Sidecar pattern. Infrastructure layer.",
            "How do you handle advanced error handling and recovery?": "Exception handlers, retry logic, fallbacks. Circuit breakers. Dead letter queues. Monitoring.",
        }
    }
};
