// Security Engineer Interview Answers
export const SECURITY_ANSWERS = {
    networkSecurity: {
        easy: {
            "What is a firewall and how does it work?": "Firewall monitors and controls network traffic based on security rules. Types: Packet filtering (IP/port), Stateful (tracks connections), Application layer (deep inspection). Can be hardware or software. First line of defense for networks.",
            "What is the difference between TCP and UDP?": "TCP: Connection-oriented, reliable delivery, ordered packets, handshake (SYN-ACK), error checking. UDP: Connectionless, faster, no guarantee, used for streaming/DNS. TCP for reliability, UDP for speed.",
            "What is a VPN and how does it work?": "VPN (Virtual Private Network) creates encrypted tunnel over public network. Encrypts traffic, hides IP, provides privacy. Types: Site-to-site, Remote access. Protocols: OpenVPN, IPSec, WireGuard.",
            "What is the OSI model and its layers?": "OSI has 7 layers: 1-Physical, 2-Data Link, 3-Network (IP), 4-Transport (TCP/UDP), 5-Session, 6-Presentation, 7-Application. Security relevant at each layer. Helps understand attack vectors.",
            "What is the difference between HTTP and HTTPS?": "HTTP: Plaintext, port 80, insecure. HTTPS: HTTP + TLS/SSL encryption, port 443, secure. HTTPS encrypts data, authenticates server, ensures integrity. Essential for sensitive data.",
            "What is an IP address?": "IP address uniquely identifies device on network. IPv4: 32-bit (e.g., 192.168.1.1). IPv6: 128-bit. Static (fixed) or Dynamic (DHCP assigned). Used for routing packets.",
            "What is DNS and how does it work?": "DNS translates domain names to IP addresses. Hierarchical: Root → TLD → Domain → Subdomain. Security concerns: DNS spoofing, hijacking. DNSSEC provides authentication.",
            "What is a MAC address?": "MAC (Media Access Control) is hardware identifier for network interface. 48-bit, usually permanent. Used in Layer 2 switching. Can be spoofed (MAC spoofing attack).",
            "What is the difference between public and private IP addresses?": "Public IP: Globally unique, internet routable. Private IP: Local network only (10.x.x.x, 192.168.x.x, 172.16-31.x.x). NAT translates private to public. Private IPs not reachable from internet directly.",
            "What is a port and what are common port numbers?": "Port is logical endpoint for communication. 0-65535 range. Common: 22 (SSH), 80 (HTTP), 443 (HTTPS), 3389 (RDP), 53 (DNS), 25 (SMTP). Port scanning reveals open services.",
        },
        medium: {
            "What is a DDoS attack and how do you prevent it?": "DDoS floods target with traffic from multiple sources. Types: Volumetric, Protocol, Application layer. Prevention: CDN, rate limiting, traffic analysis, scrubbing services, overprovisioning, WAF.",
            "What is network segmentation and why is it important?": "Segmentation divides network into isolated zones. Limits lateral movement, contains breaches, reduces attack surface. Implement with VLANs, firewalls, ACLs. Critical for defense in depth.",
            "What is an IDS vs IPS?": "IDS (Intrusion Detection): Monitors and alerts on threats, passive. IPS (Intrusion Prevention): Detects and blocks threats, active. IDS for visibility, IPS for prevention. Often combined.",
            "How does a man-in-the-middle (MITM) attack work?": "Attacker intercepts communication between parties. Methods: ARP spoofing, DNS hijacking, SSL stripping. Victim unaware. Prevention: HTTPS, certificate pinning, HSTS, VPN.",
            "What is ARP poisoning?": "ARP poisoning sends fake ARP messages linking attacker's MAC to victim's IP. Enables MITM attacks on LAN. Prevention: Static ARP entries, ARP inspection, network segmentation.",
            "What is SSL/TLS and how does the handshake work?": "SSL/TLS encrypts communication. Handshake: Client hello → Server hello + certificate → Key exchange → Encrypted session. Provides confidentiality, integrity, authentication. TLS 1.3 is current standard.",
            "What is a proxy server and how does it enhance security?": "Proxy intermediates between client and internet. Benefits: Content filtering, caching, anonymity, logging. Forward proxy for clients, reverse proxy for servers. Can inspect SSL with interception.",
            "What is port scanning and how do you detect it?": "Port scanning probes for open ports/services. Tools: Nmap. Detection: IDS, firewall logs, rate limiting, honeypots. Prevention: Close unnecessary ports, firewall rules.",
            "What is a DMZ in network security?": "DMZ (Demilitarized Zone) is isolated network segment for public-facing services. Protected by firewalls on both sides. Separates public services from internal network. Limits breach impact.",
            "What is the difference between stateful and stateless firewall?": "Stateless: Filters individual packets, no connection tracking, faster. Stateful: Tracks connection state, context-aware, more secure. Modern firewalls are stateful. Stateless for high-speed, simple filtering.",
        },
        hard: {
            "How do you secure a network against advanced persistent threats (APTs)?": "APT defense: Network segmentation, endpoint detection (EDR), threat intelligence, continuous monitoring, user behavior analytics, privileged access management, regular penetration testing, security awareness training.",
            "What is zero trust network architecture?": "Zero trust: Never trust, always verify. Principles: Verify explicitly, least privilege, assume breach. Components: Identity verification, microsegmentation, continuous monitoring. No implicit trust based on location.",
            "How do you implement network access control (NAC)?": "NAC controls device access to network. Components: Authentication, endpoint compliance check, policy enforcement. 802.1X for port-based authentication. Quarantine non-compliant devices.",
            "What is BGP hijacking and how do you prevent it?": "BGP hijacking announces false routes to redirect traffic. Prevention: RPKI (cryptographic verification), BGP monitoring, prefix filtering, route validation. Impacts internet routing at large scale.",
            "How do you detect lateral movement in a network?": "Detect lateral movement: Monitor authentication logs, network flows, unusual access patterns, privilege escalation. Tools: SIEM, EDR, user behavior analytics. Honeypots attract attackers.",
            "What is DNS tunneling and how do you detect it?": "DNS tunneling encodes data in DNS queries to bypass security. Detection: Unusual query volume, long domains, entropy analysis, payload inspection. Prevention: DNS filtering, monitoring.",
            "How do you secure IoT devices on a network?": "IoT security: Network segmentation, change default credentials, firmware updates, disable unnecessary services, network monitoring, device inventory, encryption. Assume devices are vulnerable.",
            "What is microsegmentation?": "Microsegmentation creates granular security zones. Software-defined, workload-based isolation. Prevents lateral movement. Implemented via SDN, host-based firewalls. Zero trust component.",
            "How do you implement SIEM effectively?": "SIEM: Centralized log collection, correlation, alerting. Success factors: Define use cases, tune rules, reduce false positives, integrate threat intelligence, automate response, skilled analysts.",
            "What is network forensics and how is it performed?": "Network forensics: Capture, record, analyze traffic for investigation. Tools: Wireshark, tcpdump, NetFlow. Capture packets, analyze protocols, reconstruct sessions, timeline analysis. Chain of custody important.",
        }
    },
    applicationSecurity: {
        easy: {
            "What is SQL injection?": "SQL injection inserts malicious SQL into queries. Allows data theft, modification, deletion. Example: ' OR '1'='1. Prevention: Parameterized queries, input validation, ORM, least privilege database accounts.",
            "What is Cross-Site Scripting (XSS)?": "XSS injects malicious scripts into web pages viewed by others. Types: Stored, Reflected, DOM-based. Enables session hijacking, defacement. Prevention: Output encoding, CSP, input validation.",
            "What is Cross-Site Request Forgery (CSRF)?": "CSRF tricks authenticated user into performing unwanted actions. Attacker creates malicious request. Prevention: CSRF tokens, SameSite cookies, verify origin header, re-authentication for sensitive actions.",
            "What is input validation?": "Input validation verifies user input before processing. Whitelist (allow known good) preferred over blacklist. Validate: Type, length, format, range. Client-side + server-side validation required.",
            "What is the principle of least privilege?": "Least privilege: Grant minimum permissions needed for task. Limit blast radius of compromise. Apply to users, applications, processes. Regular access reviews. Defense in depth component.",
            "What is authentication vs authorization?": "Authentication: Verifying identity (who are you?). Authorization: Verifying permissions (what can you do?). AuthN first, then AuthZ. Different mechanisms and controls for each.",
            "What are cookies and how are they used in security?": "Cookies store data in browser. Security concerns: Session hijacking, XSS. Flags: Secure (HTTPS only), HttpOnly (no JS access), SameSite (CSRF protection). Store session tokens securely.",
            "What is a session and how do you secure it?": "Session maintains user state across requests. Security: Random session IDs, regenerate after login, timeout, secure storage, HTTPS only, invalidate on logout. Prevent session fixation.",
            "What is the OWASP Top 10?": "OWASP Top 10 lists critical web security risks. Current: Injection, Broken Auth, Sensitive Data Exposure, XXE, Broken Access Control, Security Misconfiguration, XSS, Insecure Deserialization, Components with Vulnerabilities, Insufficient Logging.",
            "What is secure coding?": "Secure coding practices prevent vulnerabilities. Includes: Input validation, output encoding, authentication, access control, error handling, cryptography usage, secure defaults, defense in depth.",
            "What is HTTPS and why is it important for web security?": "HTTPS encrypts HTTP using TLS. Provides: Confidentiality (encryption), Integrity (tampering detection), Authentication (certificate verification). Essential for any sensitive data, SEO ranking factor.",
            "What is a security header?": "Security headers instruct browser on security policies. Examples: Content-Security-Policy (XSS prevention), X-Frame-Options (clickjacking), Strict-Transport-Security (HSTS), X-Content-Type-Options. Implement on server.",
        },
        medium: {
            "How do you prevent SQL injection attacks?": "Prevention: Parameterized queries/prepared statements, ORM with parameter binding, stored procedures, input validation, least privilege DB accounts, WAF. Never concatenate user input into queries.",
            "What is the difference between stored and reflected XSS?": "Stored XSS: Malicious script saved on server, affects all viewers. Reflected: Script in URL, affects clicked users. Stored more dangerous (persistent). Both require output encoding.",
            "How do you implement secure authentication?": "Secure auth: Strong password policy, bcrypt/Argon2 hashing, MFA, account lockout, secure password reset, session management, rate limiting, secure credential storage, audit logging.",
            "What is JWT and how do you use it securely?": "JWT: JSON Web Token for stateless authentication. Security: Use strong secrets, short expiration, validate signature, check claims, HTTPS only, store securely (not localStorage for sensitive). Consider refresh tokens.",
            "What is OAuth 2.0 and how does it work?": "OAuth 2.0: Authorization framework for delegated access. Flows: Authorization Code (most secure), Implicit, Client Credentials, Resource Owner. Returns access tokens. PKCE for mobile apps.",
            "What is password hashing and which algorithms should be used?": "Password hashing converts passwords to irreversible digests. Use: Argon2 (recommended), bcrypt, scrypt. Not MD5/SHA1 (fast, vulnerable). Include salt, use adaptive cost factor.",
            "What is a security misconfiguration?": "Security misconfiguration: Default credentials, unnecessary features enabled, verbose errors, missing patches, insecure permissions. Common vulnerability. Regular audits, hardening guides, automation help.",
            "How do you perform secure code review?": "Code review: Check for OWASP Top 10, authentication/authorization, input handling, cryptography usage, error handling.Manual review + automated tools (SAST). Security champions, checklists.",
            "What is SAST vs DAST?": "SAST: Static analysis of source code, finds issues early, false positives. DAST: Dynamic testing of running app, realistic results, later in cycle. Use both for comprehensive coverage.",
            "What is Content Security Policy (CSP)?": "CSP header controls resources browser can load. Prevents XSS by restricting scripts, styles, images sources. Directives: script-src, style-src, default-src. Start with report-only mode.",
            "How do you protect against clickjacking?": "Clickjacking: Invisible overlay tricks clicks. Prevention: X-Frame-Options header (DENY/SAMEORIGIN), frame-ancestors CSP directive, JavaScript frame busting (less reliable).",
            "What is insecure deserialization?": "Insecure deserialization: Untrusted data triggers code execution during deserialization. Can lead to RCE. Prevention: Avoid deserializing untrusted data, integrity checks, type checking, minimal permissions.",
        },
        hard: {
            "How do you implement a Web Application Firewall (WAF)?": "WAF: Layer 7 firewall for web apps. Deployment: Cloud (AWS WAF, Cloudflare) or on-prem. Configure rules for OWASP Top 10, custom rules, IP blocking. Tune to reduce false positives. Use with secure coding.",
            "What is threat modeling and how do you perform it?": "Threat modeling identifies threats and countermeasures. Process: Define scope, identify assets, decompose application, identify threats (STRIDE), prioritize, mitigate. Tools: OWASP Threat Dragon, Microsoft TMT.",
            "How do you secure microservices architecture?": "Microservices security: Service mesh (mTLS), API gateway, service-to-service authentication, network segmentation, centralized secrets management, container security, observability, zero trust.",
            "What is API security and best practices?": "API security: Authentication (OAuth/API keys), authorization, input validation, rate limiting, HTTPS, proper error handling, API versioning, logging, OpenAPI/Swagger documentation, security testing.",
            "How do you implement DevSecOps?": "DevSecOps: Security integrated into CI/CD. Components: SAST in pipeline, dependency scanning, DAST, container scanning, IaC scanning, security gates, security training, automated compliance.",
            "What is runtime application self-protection (RASP)?": "RASP: Security built into application runtime. Detects and blocks attacks in real-time. Monitors execution, validates inputs, blocks exploits. Complements WAF, works from inside app.",
            "How do you secure container applications?": "Container security: Minimal base images, scan for vulnerabilities, no root user, read-only filesystem, secrets management (not in images), network policies, runtime protection, image signing.",
            "What is software composition analysis (SCA)?": "SCA: Identifies open-source components and their vulnerabilities. Scans dependencies, alerts on CVEs. Tools: Snyk, Dependabot, OWASP Dependency-Check. Part of secure SDLC.",
            "How do you handle security in CI/CD pipelines?": "Pipeline security: Access control, secret management, artifact signing, vulnerability scanning, policy as code, audit logging, separated environments, infrastructure security.",
            "What is the STRIDE threat model?": "STRIDE: Spoofing, Tampering, Repudiation, Information disclosure, Denial of service, Elevation of privilege. Framework for categorizing threats. Map to security properties. Guides countermeasures.",
            "How do you perform penetration testing on web applications?": "Web pentesting: Reconnaissance, vulnerability scanning, authentication testing, session management, injection testing, access control testing, business logic testing. Follow OWASP Testing Guide. Report findings.",
        }
    },
    cryptography: {
        easy: {
            "What is encryption?": "Encryption converts plaintext to ciphertext using algorithm and key. Only those with key can decrypt. Types: Symmetric (same key), Asymmetric (public/private keys). Provides confidentiality.",
            "What is the difference between symmetric and asymmetric encryption?": "Symmetric: Same key for encrypt/decrypt, faster, key distribution problem. Asymmetric: Public key encrypts, private decrypts, slower, solves distribution. Often combined: Asymmetric for key exchange, symmetric for data.",
            "What is a hash function?": "Hash function: One-way transformation producing fixed-length digest. Properties: Deterministic, fast, collision resistant, pre-image resistant. Uses: Passwords, integrity, signatures. Not encryption (irreversible).",
            "What is a digital signature?": "Digital signature: Hash encrypted with private key. Provides: Authentication (who signed), Integrity (not modified), Non-repudiation (can't deny signing). Verified with public key.",
            "What is a certificate authority (CA)?": "CA: Trusted entity issuing digital certificates. Verifies identity, signs certificates. Chain of trust: Root CA → Intermediate CA → End entity. Browser trusts known CAs. PKI foundation.",
            "What is SSL/TLS certificate?": "TLS certificate: Digital certificate proving website identity. Contains: Public key, domain, issuer, validity. Browser verifies with CA. Types: DV, OV, EV. Essential for HTTPS.",
            "What is the purpose of a salt in hashing?": "Salt: Random data added to password before hashing. Prevents rainbow table attacks, ensures same passwords have different hashes. Should be unique per password, stored with hash.",
            "What is Base64 encoding?": "Base64: Encoding (not encryption) converting binary to ASCII text. Used for transmitting binary in text-based protocols. Not secure - easily decoded. Common in data transfer, tokens.",
        },
        medium: {
            "What is AES encryption and how does it work?": "AES: Advanced Encryption Standard, symmetric block cipher. Block sizes: 128 bits. Key sizes: 128/192/256 bits. Modes: CBC, GCM (authenticated), CTR. Standard for encryption. Fast, secure.",
            "What is RSA encryption and how does it work?": "RSA: Asymmetric algorithm using prime factorization. Generate large primes, compute modulus and keys. Slower than symmetric. Used for: Key exchange, signatures. Key size: 2048+ bits recommended.",
            "What is the Diffie-Hellman key exchange?": "Diffie-Hellman: Protocol for secure key exchange over insecure channel. Both parties generate public/private values, exchange public, compute shared secret. Vulnerable to MITM without authentication.",
            "What is a rainbow table attack?": "Rainbow table: Precomputed table of password hashes. Attacks unsalted hashes quickly. Defense: Use salts (unique per password), strong hash algorithms (bcrypt), key stretching.",
            "What is a digital certificate and how does PKI work?": "Digital certificate binds public key to identity. PKI: Infrastructure for issuing, managing certificates. Components: CA, RA, certificate store. Trust chain enables verification. X.509 standard.",
            "What is the difference between MD5, SHA-1, and SHA-256?": "MD5: 128-bit, broken (collisions found). SHA-1: 160-bit, deprecated. SHA-256: 256-bit, secure, recommended. Use SHA-256 or SHA-3 for security. Never MD5/SHA-1 for security purposes.",
            "What is key management and why is it important?": "Key management: Generation, distribution, storage, rotation, destruction of crypto keys. Critical - compromised keys = compromised data. Use HSMs, key management services, automate rotation.",
            "What is elliptic curve cryptography (ECC)?": "ECC: Asymmetric cryptography using elliptic curves. Smaller keys than RSA for same security (256-bit ECC ≈ 3072-bit RSA). Faster, less resource use. Used in TLS, mobile.",
            "What is a nonce in cryptography?": "Nonce: Number used once. Prevents replay attacks, ensures uniqueness. Used in authentication protocols, encryption modes (IV). Must not repeat with same key. Random or counter-based.",
        },
        hard: {
            "What are the vulnerabilities in cryptographic implementations?": "Implementation vulnerabilities: Timing attacks, padding oracle, weak random numbers, improper key storage, algorithm misuse, side-channel attacks. Use vetted libraries, follow best practices, security review.",
            "How do you implement end-to-end encryption?": "E2EE: Only endpoints can decrypt. Implementation: Key exchange (Diffie-Hellman), message encryption (AES), key verification, forward secrecy, device/key management. Signals protocol as reference.",
            "What is homomorphic encryption?": "Homomorphic encryption: Compute on encrypted data without decryption. Types: Partially, Somewhat, Fully homomorphic. Use cases: Cloud computing privacy. Currently expensive computationally.",
            "What is quantum cryptography and its implications?": "Quantum computing threatens current asymmetric crypto (RSA, ECC). Post-quantum cryptography being standardized (NIST). Quantum key distribution offers theoretical security. Prepare for crypto agility.",
            "How do you handle cryptographic key rotation?": "Key rotation: Regular replacement of keys. Automated process, proper key versioning, re-encrypt data or dual-key period, secure key destruction. Reduces exposure window if compromised.",
            "What is perfect forward secrecy?": "PFS: Compromise of long-term keys doesn't compromise past sessions. Use ephemeral Diffie-Hellman keys per session. If server key leaked, past traffic safe. TLS 1.3 requires it.",
            "How do you secure key storage?": "Secure key storage: HSMs for critical keys, encrypted keystores, access controls, key separation, audit logging. Never in code/config. Use cloud KMS services. Regular access reviews.",
            "What is hardware security module (HSM)?": "HSM: Tamper-resistant hardware for crypto operations and key storage. Generates, stores keys securely. FIPS certified. Used for: CA keys, payment processing, high-security applications.",
        }
    },
    cloudSecurity: {
        easy: {
            "What is cloud security?": "Cloud security: Protecting cloud infrastructure, data, applications. Addresses: IAM, data protection, network security, compliance. Shared responsibility between provider and customer.",
            "What is the shared responsibility model?": "Shared responsibility: Provider secures infrastructure (physical, hypervisor), Customer secures data, applications, access. Varies by service model. SaaS: Mostly provider. IaaS: Mostly customer.",
            "What is IAM (Identity and Access Management)?": "IAM: Managing identities and their access permissions. Components: Users, groups, roles, policies. Principle of least privilege. Enables: Authentication, authorization, audit. Cloud IAM is critical.",
            "What are security groups in cloud?": "Security groups: Virtual firewalls controlling inbound/outbound traffic. Stateful (return traffic allowed). Define rules by port, protocol, source/destination. Applied to instances.",
            "What is the difference between public, private, and hybrid cloud?": "Public: Shared infrastructure, provider managed (AWS, Azure). Private: Dedicated to organization, more control. Hybrid: Combination, workloads across both. Security considerations differ for each.",
            "What is multi-factor authentication (MFA)?": "MFA: Requires multiple authentication factors. Something you: Know (password), Have (phone), Are (biometric). Dramatically reduces account compromise. Should be mandatory for privileged access.",
            "What are access control lists (ACLs)?": "ACLs: List of permissions attached to resources. Network ACLs control subnet traffic (stateless). S3 ACLs control object access. More granular control than security groups alone.",
            "What is encryption at rest vs encryption in transit?": "Encryption at rest: Data encrypted when stored (disks, databases). In transit: Data encrypted during transmission (TLS). Both needed for complete data protection. Use strong algorithms.",
        },
        medium: {
            "How do you secure S3 buckets?": "S3 security: Block public access by default, bucket policies, ACLs, encryption (SSE-S3, SSE-KMS), versioning, access logging, VPC endpoints, Object Lock for immutability. Regular audits.",
            "What is AWS Security Hub?": "Security Hub: AWS centralized security view. Aggregates findings from GuardDuty, Inspector, Macie. Security standards (CIS, PCI). Priority findings, automated response. Multi-account support.",
            "How do you implement least privilege in cloud IAM?": "Cloud least privilege: Start with no permissions, add as needed. Use managed policies, avoid wildcards, service-specific policies, regular access reviews, IAM Access Analyzer, permission boundaries.",
            "What is cloud workload protection?": "Cloud workload protection: Securing VMs, containers, serverless. Components: Vulnerability management, runtime protection, file integrity monitoring, network security. Shift left + runtime defense.",
            "How do you detect misconfigurations in cloud?": "Detection: Cloud-native tools (Security Hub, Security Center), CSPM solutions, IaC scanning, continuous compliance checks, automated remediation. Common issues: Public access, missing encryption, excessive permissions.",
            "What is CASB (Cloud Access Security Broker)?": "CASB: Security policy enforcement between users and cloud services. Visibility into shadow IT, data protection, access control, threat prevention. Deploy inline or API-based.",
            "How do you secure serverless functions?": "Serverless security: Least privilege IAM roles, input validation, secure dependencies, environment variables for secrets, VPC placement, monitoring/logging. Short execution reduces attack window.",
            "What is cloud security posture management (CSPM)?": "CSPM: Continuous monitoring for cloud misconfigurations. Automated checks against benchmarks, risk prioritization, remediation guidance. Tools: Prisma Cloud, AWS Config, Azure Policy.",
            "How do you handle secrets management in cloud?": "Secrets management: Use dedicated services (AWS Secrets Manager, Vault), not environment variables/code. Encryption, access control, rotation, audit logging. SDK integration for applications.",
        },
        hard: {
            "How do you implement zero trust in cloud environments?": "Cloud zero trust: Strong identity verification (MFA), microsegmentation, device trust, continuous monitoring, least privilege, encrypted communications, context-aware access. Identity is new perimeter.",
            "What is container security in cloud?": "Container security: Secure base images, vulnerability scanning, image signing, admission control, runtime protection, network policies, secrets management, logging. Kubernetes security contexts.",
            "How do you detect and respond to cloud breaches?": "Cloud breach response: CloudTrail/activity logs, GuardDuty/threat detection, automated alerting, incident runbooks, forensics (snapshot instances), contain (revoke access, isolate), eradicate, recover.",
            "What is cloud-native security architecture?": "Cloud-native security: Security embedded in application design. Service mesh security, container-native controls, infrastructure as code security, API security, observability, automated compliance.",
            "How do you audit cloud infrastructure?": "Cloud auditing: Enable logging (CloudTrail, ActivityLog), centralize logs, automated compliance checks, regular access reviews, penetration testing, third-party audits, map to frameworks (CIS).",
            "What is infrastructure as code (IaC) security?": "IaC security: Scan templates before deployment. Tools: tfsec, Checkov, cfn-nag. Check for misconfigurations, secrets exposure, compliance violations. Integrate into CI/CD. Prevent issues at source.",
            "How do you handle compliance in multi-cloud environments?": "Multi-cloud compliance: Unified visibility tools, common security controls, centralized policy management, cross-cloud identity, consistent encryption, compliance automation, regular audits.",
            "What is cloud forensics?": "Cloud forensics: Investigating incidents in cloud. Challenges: Ephemeral resources, shared infrastructure, jurisdiction. Methods: Log analysis, snapshots, memory acquisition. Prepare with logging enabled.",
        }
    },
    incidentResponse: {
        easy: {
            "What is incident response?": "Incident response: Organized approach to managing security incidents. Goal: Minimize damage, reduce recovery time, prevent recurrence. Components: Preparation, detection, containment, eradication, recovery, lessons learned.",
            "What are the phases of incident response?": "IR phases: 1. Preparation (plan, tools, training), 2. Identification (detect, analyze), 3. Containment (limit damage), 4. Eradication (remove threat), 5. Recovery (restore), 6. Lessons Learned (improve).",
            "What is a security incident?": "Security incident: Event that threatens confidentiality, integrity, or availability. Examples: Data breach, malware infection, DDoS, unauthorized access. Severity levels guide response priority.",
            "What is log analysis?": "Log analysis: Examining system/application logs for security events. Sources: System, application, security, network logs. Tools: SIEM, ELK stack. Identifies anomalies, attack patterns, compliance.",
            "What is vulnerability scanning?": "Vulnerability scanning: Automated testing for known vulnerabilities. Tools: Nessus, Qualys, OpenVAS. Scans: Network, web application, authenticated/unauthenticated. Regular scanning, prioritized remediation.",
            "What is a security operations center (SOC)?": "SOC: Centralized security monitoring team. Functions: Monitoring, detection, response, threat intelligence. 24/7 coverage typical. Uses SIEM, EDR, ticketing. Tiers for escalation.",
            "What is the difference between vulnerability and exploit?": "Vulnerability: Weakness that could be exploited. Exploit: Method/code that takes advantage of vulnerability. Vulnerability without exploit still risky. Patches address vulnerabilities.",
        },
        medium: {
            "How do you create an incident response plan?": "IR plan: Define team/roles, classification criteria, communication procedures, containment strategies, evidence handling, recovery procedures, stakeholder notification, post-incident review. Test regularly with tabletop exercises.",
            "What is the role of a SIEM in incident response?": "SIEM in IR: Centralized log collection, real-time correlation, alerting, investigation support, reporting. Enables faster detection, provides context, audit trail. Core SOC technology.",
            "How do you prioritize security incidents?": "Incident priority: Based on impact (affected systems, data sensitivity, business criticality) and urgency (active threat, spreading). Use severity matrix. Focus resources on high-priority incidents.",
            "What is threat hunting?": "Threat hunting: Proactive search for threats that evade detection. Hypothesis-driven investigation. Uses threat intelligence, behavioral analysis. Assumes breach. Finds advanced threats.",
            "How do you perform root cause analysis?": "Root cause analysis: Identify underlying cause, not just symptoms. Methods: 5 Whys, fishbone diagram. Examine: Technical controls, processes, people factors. Drives preventive improvements.",
            "What is chain of custody in digital forensics?": "Chain of custody: Documentation tracking evidence handling. Includes: Who, what, when, where for each transfer. Ensures evidence integrity, admissibility in court. Critical for legal cases.",
            "How do you collect and preserve digital evidence?": "Evidence collection: Document scene, create forensic images (bit-by-bit copy), hash verification, write blockers, secure storage. Don't modify original. Follow standard procedures. Chain of custody.",
        },
        hard: {
            "How do you respond to a ransomware attack?": "Ransomware response: Isolate affected systems, determine scope, identify variant, check for decryptors, restore from backups (verify clean), don't pay if possible, report to authorities, post-incident hardening.",
            "What is memory forensics and how is it performed?": "Memory forensics: Analyzing RAM for evidence. Captures: Running processes, network connections, encryption keys, malware. Tools: Volatility, Rekall. Dump memory before shutdown. Reveals hidden threats.",
            "How do you handle an APT incident?": "APT response: Extended investigation, assume persistence, careful containment (don't alert attacker), comprehensive eradication, long-term monitoring. May require external expertise. Coordinate with legal/management.",
            "What is malware analysis?": "Malware analysis: Understanding malicious code. Static: Code/structure analysis without execution. Dynamic: Behavior analysis in sandbox. Identifies: Capabilities, IOCs, attribution hints. Specialized skill.",
            "How do you build a threat intelligence program?": "Threat intelligence: Collect, analyze, share threat info. Sources: Open source, commercial feeds, ISACs, internal. Operationalize: Feed to detection tools, inform hunting, guide priorities. Measure effectiveness.",
            "What is the MITRE ATT&CK framework?": "ATT&CK: Knowledge base of attacker tactics and techniques. Used for: Detection coverage mapping, threat hunting, red teaming, security assessment. Categories: Initial access through impact. Industry standard.",
        }
    },
    complianceRisk: {
        easy: {
            "What is a security policy?": "Security policy: Document defining security rules and expectations. Types: Acceptable use, password, incident response, data classification. Foundation of security program. Must be enforced, reviewed regularly.",
            "What is risk assessment?": "Risk assessment: Identifying and evaluating risks. Steps: Asset identification, threat identification, vulnerability assessment, likelihood/impact analysis, risk rating. Prioritizes security investments.",
            "What is GDPR?": "GDPR: EU data protection regulation. Key requirements: Consent, right to access/erasure, breach notification (72hrs), data protection by design, DPO requirement, hefty fines. Applies globally for EU data.",
            "What is PCI DSS?": "PCI DSS: Payment card industry standard. 12 requirements covering: Network security, data protection, access control, monitoring, testing, policies. Required for processing card payments. Validated annually.",
            "What is HIPAA?": "HIPAA: US healthcare data protection law. Covers: PHI protection, privacy rule, security rule, breach notification. Technical, physical, administrative safeguards required. Applies to healthcare entities.",
        },
        medium: {
            "How do you perform a security audit?": "Security audit: Systematic evaluation of security posture. Steps: Define scope, gather evidence, test controls, interview personnel, analyze findings, report with recommendations. Can be internal or external.",
            "What is the difference between vulnerability assessment and penetration testing?": "Vulnerability assessment: Automated scanning for known vulnerabilities, broad coverage, less depth. Penetration testing: Simulated attack, attempts exploitation, proves impact. VA for breadth, pentest for depth.",
            "What is a security framework (NIST, ISO 27001)?": "Security frameworks: Structured approach to security. NIST CSF: Identify, Protect, Detect, Respond, Recover. ISO 27001: ISMS certification. CIS Controls: Prioritized actions. Guide security program development.",
            "How do you calculate risk?": "Risk calculation: Risk = Likelihood × Impact. Qualitative (High/Medium/Low) or Quantitative (dollar values). Consider: Threat capability, vulnerability severity, asset value. Enables prioritization.",
            "What is data classification?": "Data classification: Categorizing data by sensitivity. Typical levels: Public, Internal, Confidential, Restricted. Determines: Access controls, encryption, handling procedures. Foundation for data protection.",
        },
        hard: {
            "How do you build a security awareness program?": "Awareness program: Regular training, phishing simulations, communications, metrics tracking. Topics: Phishing, passwords, social engineering, data handling. Tailor to roles. Measure behavior change.",
            "What is SOC 2 compliance?": "SOC 2: Trust service criteria for service organizations. Categories: Security, Availability, Processing Integrity, Confidentiality, Privacy. Audit by CPA. Type 1 (point in time) vs Type 2 (period). Customer assurance.",
            "How do you handle third-party risk management?": "Third-party risk: Assess vendor security before engagement. Methods: Questionnaires, audits, certifications review. Ongoing monitoring. Contractual security requirements. Criticality-based assessment depth.",
            "What is business continuity planning?": "BCP: Ensuring operations continue during disruptions. Components: BIA (identify critical functions), recovery strategies, plan documentation, testing. Related to disaster recovery. RTO/RPO targets.",
            "How do you implement a security governance program?": "Security governance: Leadership, policies, accountability structure. Components: Security committee, CISO role, policy framework, risk management, compliance management, metrics/reporting. Aligns security with business.",
        }
    }
};
